<?php
declare(strict_types=1);
namespace Sinaesta\Identity\Application;
use Sinaesta\Identity\Infrastructure\AuthRepository;
use Sinaesta\Shared\Http\HttpException;
final readonly class AuthService
{
    public function __construct(private AuthRepository $repository) {}
    public function register(array $input): array { $errors=$this->validateRegistration($input); if($errors!==[])throw new HttpException(422,'Validasi gagal',$errors); $email=strtolower(trim((string)$input['email'])); if($this->repository->findUserByEmail($email)!==null)throw new HttpException(409,'Email sudah terdaftar.'); $this->repository->pdo()->beginTransaction(); try { $public=bin2hex(random_bytes(16)); $id=$this->repository->createUser($public,trim((string)$input['name']),$email,password_hash((string)$input['password'],PASSWORD_DEFAULT)); $this->repository->createProfile($id,trim((string)$input['name'])); $token=$this->newOneTimeToken('email_verification_tokens',$id,86400); $this->repository->pdo()->commit(); return ['user'=>['id'=>$public,'name'=>trim((string)$input['name']),'email'=>$email,'email_verified_at'=>null],'verification_token'=>$this->exposeDevelopmentToken($token)]; } catch(\Throwable $e){if($this->repository->pdo()->inTransaction())$this->repository->pdo()->rollBack();throw $e;} }
    public function login(array $input,string $agent,string $ip): array { $email=strtolower(trim((string)($input['email']??''))); $password=(string)($input['password']??''); if($email===''||$password==='')throw new HttpException(422,'Validasi gagal',['email'=>$email===''?['Email wajib diisi.']:[],'password'=>$password===''?['Password wajib diisi.']:[]]); $user=$this->repository->findUserByEmail($email); $ipHash=$this->ipHash($ip); if($user===null||!password_verify($password,(string)$user['password_hash'])){ $this->repository->loginHistory($user['id']??null,$email,'failure',$agent,$ipHash); throw new HttpException(401,'Email atau password salah.'); } if($user['status']!=='active')throw new HttpException(403,'Akun tidak aktif.'); if(password_needs_rehash((string)$user['password_hash'],PASSWORD_DEFAULT))$this->repository->updatePassword((int)$user['id'],password_hash($password,PASSWORD_DEFAULT)); $raw=rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'='); $expires=gmdate('Y-m-d H:i:s',time()+max(300,(int)(getenv('AUTH_SESSION_TTL')?:7200))); $sessionId=bin2hex(random_bytes(16)); $this->repository->createSession((int)$user['id'],$sessionId,hash('sha256',$raw),$expires,$agent,$ipHash); $this->repository->loginHistory((int)$user['id'],$email,'success',$agent,$ipHash); return ['token'=>$raw,'token_type'=>'Bearer','expires_at'=>$expires,'session_id'=>$sessionId,'user'=>$this->publicUser($user)]; }
    public function forgot(string $email): void { $user=$this->repository->findUserByEmail(strtolower(trim($email))); if($user!==null&&$user['status']==='active')$this->newOneTimeToken('password_reset_tokens',(int)$user['id'],3600); }
    public function reset(string $token,string $password,string $confirmation): void { $this->assertPassword($password,$confirmation); $id=$this->repository->consumeToken('password_reset_tokens',hash('sha256',$token)); if($id===null)throw new HttpException(422,'Token reset tidak valid atau kedaluwarsa.'); $this->repository->updatePassword($id,password_hash($password,PASSWORD_DEFAULT));$this->repository->revokeAllSessions($id); }
    public function change(array $user,string $current,string $password,string $confirmation): void { $record=$this->repository->findUserByPublicId((string)$user['public_id']); if($record===null||!password_verify($current,(string)$record['password_hash']))throw new HttpException(422,'Password saat ini salah.',['current_password'=>['Password saat ini salah.']]); $this->assertPassword($password,$confirmation);$this->repository->updatePassword((int)$user['internal_id'],password_hash($password,PASSWORD_DEFAULT));$this->repository->revokeAllSessions((int)$user['internal_id']); }
    public function verificationToken(int $id): ?string { return $this->exposeDevelopmentToken($this->newOneTimeToken('email_verification_tokens',$id,86400)); }
    public function verify(string $token): void { $id=$this->repository->consumeToken('email_verification_tokens',hash('sha256',$token));if($id===null)throw new HttpException(422,'Token verifikasi tidak valid atau kedaluwarsa.');$this->repository->verifyEmail($id); }
    public function publicUser(array $u): array { return ['id'=>$u['public_id'],'name'=>$u['name'],'email'=>$u['email'],'status'=>$u['status'],'email_verified_at'=>$u['email_verified_at']]; }
    private function validateRegistration(array $i): array { $e=[];$name=trim((string)($i['name']??''));$email=trim((string)($i['email']??''));$p=(string)($i['password']??'');if($name===''||mb_strlen($name)>120)$e['name']=['Nama wajib diisi dan maksimal 120 karakter.'];if(!filter_var($email,FILTER_VALIDATE_EMAIL))$e['email']=['Email tidak valid.'];if(strlen($p)<12)$e['password']=['Password minimal 12 karakter.'];if($p!==($i['password_confirmation']??null))$e['password_confirmation']=['Konfirmasi password tidak cocok.'];if(($i['accepted_terms']??false)!==true)$e['accepted_terms']=['Syarat wajib disetujui.'];if(($i['accepted_privacy']??false)!==true)$e['accepted_privacy']=['Kebijakan privasi wajib disetujui.'];return $e; }
    private function assertPassword(string $p,string $c): void { $e=[];if(strlen($p)<12)$e['password']=['Password minimal 12 karakter.'];if($p!==$c)$e['password_confirmation']=['Konfirmasi password tidak cocok.'];if($e!==[])throw new HttpException(422,'Validasi gagal',$e); }
    private function newOneTimeToken(string $table,int $id,int $ttl): string { $raw=rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'=');$this->repository->storeOneTimeToken($table,$id,hash('sha256',$raw),gmdate('Y-m-d H:i:s',time()+$ttl));return $raw; }
    private function exposeDevelopmentToken(string $token): ?string { return getenv('APP_ENV')==='production'?null:$token; }
    private function ipHash(string $ip): ?string { if($ip==='')return null; $parts=explode('.',$ip);if(count($parts)===4)$ip=$parts[0].'.'.$parts[1].'.'.$parts[2].'.0';return hash('sha256',$ip); }
}
