import { useQuery } from '@tanstack/react-query'
import { CalendarClock, Play, RotateCcw } from 'lucide-react'
import { api } from '@/lib/api/client'

type QueueItem={id:string;topic:string;mastery_before:number;priority:number;recovery_stage:string;last_reviewed_at:string|null;next_review_at:string;bucket:'due_today'|'overdue'|'upcoming';failure_count:number}
type Queue={items:QueueItem[];summary:Record<string,number>;snooze_limit:number}
export function ReviewQueue(){const query=useQuery({queryKey:['review-queue'],queryFn:()=>api.get<Queue>('/me/review-queue').then(r=>r.data)});if(query.isPending)return <div className="card animate-pulse">Memuat antrean review…</div>;if(query.isError)return <div className="card"><h1 className="text-2xl font-black">Smart Revision Queue</h1><p className="mt-3 text-sm text-slate-500">Antrean tidak tersedia atau paketmu belum mencakup fitur ini.</p></div>;const data=query.data;return <><p className="eyebrow">Adaptive learning</p><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="mt-2 text-3xl font-black">Smart Revision Queue</h1><p className="mt-2 text-slate-500">Review terjadwal berdasarkan performa dan kesalahan nyata.</p></div><div className="flex gap-2"><button className="btn-secondary">Review 10 Soal</button><button className="btn-primary"><Play size={16}/>Review Semua</button></div></div><section className="mt-7 grid gap-4 sm:grid-cols-4">{[['Due Today',data.summary.due_today||0],['Overdue',data.summary.overdue||0],['Upcoming',data.summary.upcoming||0],['High Priority',data.items.filter(x=>x.priority>=75).length]].map(([label,value])=><div className="card" key={label}><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>)}</section><div className="mt-6 space-y-3">{data.items.map(item=><article className="card flex flex-col justify-between gap-4 md:flex-row md:items-center" key={item.id}><div><span className="chip"><CalendarClock size={13}/>{item.bucket.replace('_',' ')}</span><h2 className="mt-3 font-bold">{item.topic}</h2><p className="mt-1 text-sm text-slate-500">{item.failure_count>1?`${item.failure_count} kali salah · perlu penguatan`:'Review terjadwal'} · Mastery {item.mastery_before}</p><p className="mt-1 text-xs text-slate-400">Jatuh tempo {new Date(item.next_review_at).toLocaleDateString('id-ID')} · tahap {item.recovery_stage}</p></div><div className="flex gap-2"><button className="btn-secondary" disabled={false}><RotateCcw size={15}/>Tunda Review</button><button className="btn-primary">Review Sekarang</button></div></article>)}{data.items.length===0&&<div className="card text-center"><h2 className="font-bold">Semua review selesai</h2><p className="mt-2 text-sm text-slate-500">Item berikutnya akan muncul sesuai jadwal spaced repetition.</p></div>}</div></>}

type Settings={mastery_weights:Record<string,number>;recommendation_rules:Record<string,number>;review_intervals:number[]}
export function AdaptiveAdmin(){const query=useQuery({queryKey:['adaptive-settings'],queryFn:()=>api.get<Settings>('/admin/adaptive-learning').then(r=>r.data)});return <><p className="eyebrow">Konfigurasi sistem</p><h1 className="mt-2 text-3xl font-black">Adaptive Learning</h1><p className="mt-2 text-slate-500">Bobot tersentralisasi dan setiap perubahan dicatat dalam audit log.</p>{query.isPending?<div className="card mt-7">Memuat konfigurasi…</div>:query.isError?<div className="card mt-7">Konfigurasi tidak dapat dimuat.</div>:<div className="mt-7 grid gap-5 lg:grid-cols-2"><section className="card"><h2 className="font-bold">Mastery weights</h2><div className="mt-4 grid grid-cols-2 gap-3">{Object.entries(query.data.mastery_weights).map(([key,value])=><label className="text-xs font-semibold capitalize" key={key}>{key.replaceAll('_',' ')}<input className="field mt-1" type="number" value={value} readOnly/></label>)}</div></section><section className="card"><h2 className="font-bold">Recommendation rules</h2><div className="mt-4 space-y-3">{Object.entries(query.data.recommendation_rules).map(([key,value])=><label className="block text-xs font-semibold capitalize" key={key}>{key.replaceAll('_',' ')}<input className="field mt-1" type="number" value={value} readOnly/></label>)}</div><h3 className="mt-5 text-sm font-bold">Review intervals</h3><p className="mt-2 text-sm text-slate-500">{query.data.review_intervals.join(' · ')} hari</p><button className="btn-primary mt-5">Simpan konfigurasi</button></section></div>}</>}
