import { useQuery } from '@tanstack/react-query'
import { Link } from '@tanstack/react-router'
import { ArrowRight, CalendarClock, Clock3, Crown, FileCheck2, PlayCircle, Ticket } from 'lucide-react'
import { api } from '@/lib/api/client'
import { PageState } from '@/components/ui'

type Attempt={id:string;exam_name:string;exam_type:string;question_count:number;duration_seconds:number;started_at:string;expires_at:string;status:string;score?:number;correct?:number;incorrect?:number;unanswered?:number}
type Exam={id:string;name:string;type:string;category?:string;question_count:number;duration_seconds:number;starts_at?:string;ends_at?:string;access:'free'|'premium';registration_status?:string}
type Subscription={package_name:string;expires_at:string|null;token_balance:number}
const date=(value?:string)=>value?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—'
const duration=(seconds:number)=>`${Math.round(seconds/60)} menit`

export function Dashboard(){
 const attempts=useQuery({queryKey:['attempts'],queryFn:()=>api.get<Attempt[]>('/me/attempts').then(r=>r.data)})
 const exams=useQuery({queryKey:['tryouts'],queryFn:()=>api.get<Exam[]>('/tryouts').then(r=>r.data)})
 const subscription=useQuery({queryKey:['subscription'],queryFn:()=>api.get<Subscription>('/me/subscription').then(r=>r.data)})
 if(attempts.isPending||exams.isPending||subscription.isPending)return <PageState kind="loading"/>
 if(attempts.isError||exams.isError||subscription.isError)return <PageState kind="error" title="Dashboard ujian belum dapat dimuat" description="Periksa koneksi lalu muat ulang data ujian Anda." onRetry={()=>{attempts.refetch();exams.refetch();subscription.refetch()}}/>
 const active=attempts.data.find(x=>x.status==='active'), available=exams.data.filter(x=>x.type==='quick_quiz'||x.type==='quiz').slice(0,3), upcoming=exams.data.filter(x=>x.starts_at&&new Date(x.starts_at)>new Date()).slice(0,3), recent=attempts.data.filter(x=>x.status!=='active').slice(0,4)
 return <><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Pusat ujian peserta</p><h1 className="mt-2 text-3xl font-black">Siap mengerjakan ujian?</h1><p className="mt-1 text-slate-500">Pilih ujian, kerjakan, lalu lihat hasil dan pembahasan.</p></div><Link to="/app/exams" className="btn-primary">Lihat semua ujian <ArrowRight size={17}/></Link></div>
 <div className="mt-7 grid gap-6 xl:grid-cols-[1.45fr_1fr]"><div className="space-y-6"><section className="card overflow-hidden bg-ink text-white"><p className="eyebrow !text-lime">Ujian aktif</p>{active?<><div className="mt-4 flex items-start justify-between gap-5"><div><h2 className="text-xl font-bold">{active.exam_name}</h2><p className="mt-2 text-sm text-white/60">{active.exam_type} · {active.question_count} soal · {duration(active.duration_seconds)}</p><p className="mt-1 text-xs text-white/50">Berakhir {date(active.expires_at)}</p></div><PlayCircle size={42} className="text-lime"/></div><Link to="/app/attempt/$attemptId" params={{attemptId:active.id}} className="btn mt-6 bg-lime text-ink">Lanjutkan ujian</Link></>:<div className="py-7 text-sm text-white/60">Tidak ada ujian yang sedang dikerjakan.</div>}</section>
 <section className="card"><div className="flex items-center justify-between"><div><p className="eyebrow">Kuis tersedia</p><h2 className="mt-1 text-xl font-bold">Mulai kuis terbaru</h2></div><FileCheck2 className="text-brand"/></div><div className="mt-4 divide-y">{available.length?available.map(x=><div className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center" key={x.id}><div className="flex-1"><b>{x.name}</b><p className="mt-1 text-xs text-slate-500">{x.category??'Campuran'} · {x.question_count} soal · {duration(x.duration_seconds)}</p></div><span className="chip">{x.access==='free'?'Gratis':'Premium'}</span><Link to="/app/exams" className="btn-secondary min-h-9 px-3 py-1 text-xs">Lihat kuis</Link></div>):<p className="py-7 text-sm text-slate-500">Belum ada kuis yang tersedia.</p>}</div></section>
 <section className="card"><div className="flex justify-between"><div><p className="eyebrow">Riwayat terakhir</p><h2 className="mt-1 text-xl font-bold">Hasil ujian</h2></div><Link to="/app/history" className="text-sm font-bold text-brand">Semua riwayat</Link></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="py-3">Ujian</th><th>Nilai</th><th>Benar</th><th>Salah</th><th>Kosong</th></tr></thead><tbody className="divide-y">{recent.map(x=><tr key={x.id}><td className="py-4"><b>{x.exam_name}</b><p className="text-xs text-slate-500">{date(x.started_at)}</p></td><td className="font-bold text-brand">{x.score??'—'}</td><td>{x.correct??'—'}</td><td>{x.incorrect??'—'}</td><td>{x.unanswered??'—'}</td></tr>)}</tbody></table>{!recent.length&&<p className="py-7 text-sm text-slate-500">Belum ada riwayat ujian.</p>}</div></section></div>
 <div className="space-y-6"><section className="card"><Crown className="text-brand"/><p className="eyebrow mt-5">Paket saya</p><h2 className="mt-1 text-xl font-bold">{subscription.data.package_name}</h2><p className="mt-2 text-sm text-slate-500">Masa berlaku: {date(subscription.data.expires_at??undefined)}</p><div className="mt-4 flex items-center gap-2 rounded-xl bg-mist p-3"><Ticket size={18}/><b>{subscription.data.token_balance} token ujian</b></div><Link to="/app/packages" className="btn-primary mt-5 w-full">Upgrade paket</Link></section>
 <section className="card"><div className="flex items-center justify-between"><div><p className="eyebrow">Ujian mendatang</p><h2 className="mt-1 text-lg font-bold">Jadwal terdekat</h2></div><CalendarClock className="text-brand"/></div><div className="mt-4 divide-y">{upcoming.map(x=><div className="py-4" key={x.id}><b className="text-sm">{x.name}</b><p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><Clock3 size={13}/>{date(x.starts_at)}</p><span className="chip mt-2">{x.registration_status??'Terjadwal'}</span></div>)}{!upcoming.length&&<p className="py-5 text-sm text-slate-500">Belum ada jadwal mendatang.</p>}</div></section></div></div></>}
