import { AlertCircle, ArrowLeft, Check, ChevronRight, ClipboardCheck, Clock3, Copy, FileDown, FileText, History, LockKeyhole, PenLine, Plus, Printer, Save, ShieldCheck, Stethoscope, UserRound, X } from 'lucide-react'
import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { useToast } from '@/components/ui'
import { cn } from '@/lib/utils'

type Status='Draft'|'Submitted'|'Revision'|'Approved'|'Locked'
type FormData=Record<string,string>
const steps=['Registrasi','Triase','Anamnesis','Pemeriksaan fisik','Asesmen','Rencana','Resep / tindakan','Edukasi','Tindak lanjut','Finalisasi']
const initial:FormData={visitType:'Datang langsung',chiefComplaint:'Pusing sejak tiga hari',presentIllness:'Pusing berputar terutama saat bangun dari tempat tidur.',pastHistory:'Hipertensi sejak 2022',medicationHistory:'Amlodipine 5 mg, 1× sehari',allergy:'Tidak diketahui',familyHistory:'Ayah dengan hipertensi',socialHistory:'Tinggal bersama keluarga',smoking:'Tidak pernah',alcohol:'Tidak',activity:'Aktivitas ringan 2–3× per minggu',diet:'Makan teratur, konsumsi garam belum dibatasi',systolic:'148',diastolic:'92',pulse:'84',respiration:'18',temperature:'36.7',oxygen:'98',weight:'68',height:'158',waist:'91',physicalExam:'Keadaan umum baik, compos mentis. Kepala, leher, toraks, abdomen, dan ekstremitas dalam batas normal.',supportingResults:'Belum ada pemeriksaan penunjang.',workingDiagnosis:'I10 — Hipertensi esensial (primer)',differentialDiagnosis:'Vertigo perifer',therapyPlan:'Lanjutkan amlodipine 5 mg; monitor tekanan darah di rumah.',education:'Edukasi diet rendah garam, aktivitas fisik bertahap, dan tanda bahaya.',controlDate:'2026-08-14'}

function Field({label,name,data,setData,required=false,area=false,placeholder,disabled=false,type='text'}:{label:string;name:string;data:FormData;setData:(v:FormData)=>void;required?:boolean;area?:boolean;placeholder?:string;disabled?:boolean;type?:string}){const Tag=area?'textarea':'input';return <label><span className="label">{label}{required&&<span className="text-rose-600"> *</span>}</span><Tag className={cn('field',area&&'min-h-24 py-3',disabled&&'bg-slate-50 text-slate-500')} name={name} type={area?undefined:type} value={data[name]||''} placeholder={placeholder} disabled={disabled} onChange={e=>setData({...data,[name]:e.target.value})}/></label>}
function Section({eyebrow,title,children}:{eyebrow:string;title:string;children:ReactNode}){return <section className="card"><div className="mb-5 border-b pb-4"><p className="eyebrow">{eyebrow}</p><h2 className="mt-1 text-lg font-black">{title}</h2></div>{children}</section>}
function Select({label,name,data,setData,options}:{label:string;name:string;data:FormData;setData:(v:FormData)=>void;options:string[]}){return <label><span className="label">{label}</span><select className="field" value={data[name]} onChange={e=>setData({...data,[name]:e.target.value})}>{options.map(o=><option key={o}>{o}</option>)}</select></label>}

export function Examinations(){
 const [data,setData]=useState<FormData>(()=>{try{return typeof window==='undefined'?initial:{...initial,...JSON.parse(localStorage.getItem('sinaesta-exam-draft')||'{}')}}catch{return initial}});const [status,setStatus]=useState<Status>('Draft');const [active,setActive]=useState(3);const [saved,setSaved]=useState('Baru saja');const [historyOpen,setHistoryOpen]=useState(false);const [printOpen,setPrintOpen]=useState(false);const [copyOpen,setCopyOpen]=useState(false);const [addendum,setAddendum]=useState(false);const toast=useToast()
 useEffect(()=>{const id=setTimeout(()=>{localStorage.setItem('sinaesta-exam-draft',JSON.stringify(data));setSaved(new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}))},650);return()=>clearTimeout(id)},[data])
 const bmi=useMemo(()=>data.weight&&data.height?(+data.weight/(+data.height/100)**2).toFixed(1):'—',[data.weight,data.height]);const whtr=useMemo(()=>data.waist&&data.height?(+data.waist/+data.height).toFixed(2):'—',[data.waist,data.height]);const locked=status==='Locked'
 const submit=()=>{if(!data.chiefComplaint||!data.systolic||!data.workingDiagnosis||!data.therapyPlan){toast('Lengkapi field wajib sebelum mengirim');return}setStatus('Submitted');toast('Catatan berhasil diajukan untuk ditinjau')}
 return <div className="pb-24"><header className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><div className="flex items-center gap-2 text-sm text-slate-500"><span>Pelayanan klinis</span><ChevronRight size={14}/><span className="text-ink">Pemeriksaan</span></div><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-black">Pemeriksaan pasien</h1><StatusBadge status={status}/></div><p className="mt-1 text-sm text-slate-500">Kunjungan #KJ-2026-0807-014 · Jumat, 7 Agustus 2026</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>setHistoryOpen(true)}><History size={17}/> Riwayat versi</button><button className="btn-secondary" onClick={()=>setPrintOpen(true)}><Printer size={17}/> Print & PDF</button><button className="btn-primary" disabled={locked} onClick={()=>{localStorage.setItem('sinaesta-exam-draft',JSON.stringify(data));toast('Draft disimpan')}}><Save size={17}/> Simpan draft</button></div></header>
 <PatientStrip/>
 <div className="mt-5 overflow-x-auto rounded-2xl border bg-white p-3 shadow-sm"><ol className="flex min-w-max items-center">{steps.map((s,i)=><li key={s} className="flex items-center"><button onClick={()=>setActive(i)} className={cn('flex items-center gap-2 rounded-xl px-3 py-2 text-xs font-bold',i===active?'bg-brand text-white':i<active?'text-emerald-700':'text-slate-400')}><span className={cn('grid h-6 w-6 place-items-center rounded-full border',i<active&&'border-emerald-600 bg-emerald-50')}>{i<active?<Check size={13}/>:i+1}</span>{s}</button>{i<steps.length-1&&<ChevronRight className="text-slate-300" size={15}/>}</li>)}</ol></div>
 {locked&&<div className="mt-5 flex flex-col gap-3 rounded-2xl border border-violet-200 bg-violet-50 p-4 text-violet-900 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><LockKeyhole className="shrink-0"/><div><b>Catatan telah dikunci</b><p className="text-sm">Isi asli tidak dapat diubah. Setiap koreksi harus dibuat sebagai addendum.</p></div></div><button className="btn bg-violet-700 text-white" onClick={()=>setAddendum(true)}><Plus size={17}/> Buat addendum</button></div>}
 <fieldset disabled={locked} className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="space-y-5"><Section eyebrow="S · Subjective" title="Anamnesis"><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Keluhan utama" name="chiefComplaint" required data={data} setData={setData}/></div><div className="sm:col-span-2"><Field label="Riwayat penyakit sekarang" name="presentIllness" required area data={data} setData={setData}/></div>{[['Riwayat penyakit dahulu','pastHistory'],['Riwayat obat','medicationHistory'],['Riwayat alergi','allergy'],['Riwayat keluarga','familyHistory'],['Riwayat sosial','socialHistory']].map(([l,n])=><Field key={n} label={l} name={n} data={data} setData={setData}/>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Select label="Kebiasaan merokok" name="smoking" data={data} setData={setData} options={['Tidak pernah','Berhenti','Aktif']}/><Select label="Konsumsi alkohol" name="alcohol" data={data} setData={setData} options={['Tidak','Kadang-kadang','Rutin']}/><Field label="Aktivitas fisik" name="activity" data={data} setData={setData}/><div className="sm:col-span-2 lg:col-span-3"><Field label="Pola makan" name="diet" data={data} setData={setData}/></div></div></Section>
 <Section eyebrow="O · Objective" title="Tanda vital & pemeriksaan"><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{[['Sistolik','systolic','mmHg'],['Diastolik','diastolic','mmHg'],['Nadi','pulse','x/menit'],['Pernapasan','respiration','x/menit'],['Suhu','temperature','°C'],['Saturasi oksigen','oxygen','%'],['Berat badan','weight','kg'],['Tinggi badan','height','cm'],['Lingkar pinggang','waist','cm']].map(([l,n,u])=><label key={n}><span className="label">{l}{['systolic','diastolic'].includes(n)&&<span className="text-rose-600"> *</span>}</span><div className="relative"><input type="number" step="any" className="field pr-16" value={data[n]} onChange={e=>setData({...data,[n]:e.target.value})}/><span className="absolute right-3 top-3 text-xs text-slate-400">{u}</span></div></label>)}<Metric label="IMT otomatis" value={bmi} note="kg/m²"/><Metric label="Waist-to-height" value={whtr} note="rasio"/></div><div className="mt-5 grid gap-4"><Field label="Pemeriksaan fisik per sistem" name="physicalExam" area data={data} setData={setData}/><Field label="Hasil penunjang" name="supportingResults" area data={data} setData={setData}/></div></Section>
 <Section eyebrow="A · Assessment" title="Asesmen klinis"><div className="rounded-xl border border-sky-200 bg-sky-50 p-3 text-sm text-sky-800"><AlertCircle className="mr-2 inline" size={17}/><b>Pilih kode atau tulis diagnosis klinis.</b> Sistem tidak membuat diagnosis otomatis dari gejala.</div><div className="mt-4 grid gap-4"><label><span className="label">Diagnosis kerja <span className="text-rose-600">*</span></span><input list="diagnoses" className="field" value={data.workingDiagnosis} onChange={e=>setData({...data,workingDiagnosis:e.target.value})}/><datalist id="diagnoses"><option value="I10 — Hipertensi esensial (primer)"/><option value="E11.9 — Diabetes melitus tipe 2 tanpa komplikasi"/><option value="J06.9 — Infeksi saluran napas atas akut"/></datalist><p className="mt-1 text-xs text-slate-500">Kode diagnosis bersifat pilihan; teks klinis tetap dapat ditulis bebas.</p></label><Field label="Diagnosis banding" name="differentialDiagnosis" area data={data} setData={setData}/></div></Section>
 <Section eyebrow="P · Plan" title="Rencana & tindak lanjut"><div className="grid gap-4"><Field label="Rencana terapi" name="therapyPlan" required area data={data} setData={setData}/><Field label="Edukasi" name="education" area data={data} setData={setData}/><Field label="Tanggal kontrol" name="controlDate" type="date" data={data} setData={setData}/></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><button type="button" className="btn-secondary"><Plus size={17}/> Tambah resep</button><button type="button" className="btn-secondary"><Stethoscope size={17}/> Tambah tindakan</button><button type="button" className="btn-secondary"><FileText size={17}/> Buat rujukan</button></div></Section></div>
 <aside className="space-y-5"><section className="card sticky top-20"><p className="eyebrow">Kendali catatan</p><h2 className="mt-1 font-black">Finalisasi</h2><div className="mt-4 flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-xs text-emerald-700"><Check size={16}/><span>Autosave aktif · {saved}</span></div><div className="mt-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Kelengkapan wajib</p><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full w-4/5 rounded-full bg-brand"/></div><p className="mt-2 text-xs text-slate-500">4 dari 5 field wajib terisi</p></div><button type="button" className="btn-secondary mt-5 w-full" onClick={()=>setCopyOpen(true)}><Copy size={16}/> Salin kunjungan lalu</button><button type="button" className="btn-secondary mt-2 w-full" onClick={()=>toast('Template “Kontrol hipertensi” diterapkan')}><ClipboardCheck size={16}/> Gunakan template</button><div className="my-5 border-t"/><Signature/><button type="button" className="btn-primary mt-5 w-full" disabled={locked||status==='Submitted'} onClick={submit}><PenLine size={17}/> Ajukan catatan</button>{status==='Submitted'&&<button type="button" className="btn mt-2 w-full bg-emerald-700 text-white" onClick={()=>setStatus('Approved')}><ShieldCheck size={17}/> Co-sign & setujui</button>}{status==='Approved'&&<button type="button" className="btn mt-2 w-full bg-slate-900 text-white" onClick={()=>setStatus('Locked')}><LockKeyhole size={17}/> Kunci catatan</button>}</section></aside></fieldset>
 {historyOpen&&<HistoryModal onClose={()=>setHistoryOpen(false)}/>} {printOpen&&<PrintModal data={data} bmi={bmi} whtr={whtr} onClose={()=>setPrintOpen(false)}/>} {copyOpen&&<CopyModal onClose={()=>setCopyOpen(false)} onCopy={()=>{setCopyOpen(false);toast('Data terpilih berhasil disalin')}}/>} {addendum&&<Addendum onClose={()=>setAddendum(false)} onSave={()=>{setAddendum(false);toast('Addendum tersimpan tanpa mengubah catatan asli')}}/>}</div>
}

function PatientStrip(){return <section className="mt-5 flex flex-col gap-4 rounded-2xl border bg-white p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-full bg-rose-100 text-xs font-black text-rose-700">SA</span><div><b>Siti Aminah</b><p className="text-xs text-slate-500">RM-2026-001284 · Perempuan, 58 tahun</p></div></div><div className="flex flex-wrap gap-2"><span className="chip bg-rose-50 text-rose-700">Alergi: Penisilin</span><span className="chip bg-amber-50 text-amber-700">Hipertensi</span><span className="chip"><UserRound size={13} className="mr-1"/> dr. Ayu Santoso</span></div></section>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <div><span className="label">{label}</span><div className="flex min-h-11 items-center justify-between rounded-xl border bg-slate-50 px-3"><b className="text-brand">{value}</b><span className="text-xs text-slate-400">{note}</span></div></div>}
function StatusBadge({status}:{status:Status}){const colors:Record<Status,string>={Draft:'bg-amber-50 text-amber-700',Submitted:'bg-blue-50 text-blue-700',Revision:'bg-orange-50 text-orange-700',Approved:'bg-emerald-50 text-emerald-700',Locked:'bg-violet-50 text-violet-700'};return <span className={cn('chip',colors[status])}>{status}</span>}
function Signature(){return <div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Tanda tangan pemeriksa</p><div className="mt-3 rounded-xl border border-dashed p-3 text-center"><PenLine className="mx-auto text-brand" size={20}/><b className="mt-2 block text-sm">dr. Ayu Santoso</b><p className="text-xs text-slate-500">SIP 503/1287/DINKES/2026</p></div><p className="mt-3 text-xs text-slate-500">Co-sign supervisor akan diminta setelah catatan diajukan.</p></div>}
function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:ReactNode;wide?:boolean}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4"><section role="dialog" aria-modal="true" className={cn('max-h-[90vh] w-full overflow-auto rounded-2xl bg-white shadow-2xl',wide?'max-w-4xl':'max-w-lg')}><header className="sticky top-0 flex items-center justify-between border-b bg-white p-5"><h2 className="text-lg font-black">{title}</h2><button onClick={onClose} aria-label="Tutup"><X/></button></header>{children}</section></div>}
function HistoryModal({onClose}:{onClose:()=>void}){return <Modal title="Riwayat & perbandingan versi" onClose={onClose} wide><div className="p-5"><div className="grid gap-4 sm:grid-cols-2">{[['Versi 2 · Saat ini','7 Agu 2026, 10.42','dr. Ayu Santoso','Rencana terapi diperbarui'],['Versi 1','7 Agu 2026, 10.08','dr. Ayu Santoso','Catatan pemeriksaan dibuat']].map((v,i)=><article className={cn('rounded-xl border p-4',i===0&&'border-brand bg-teal-50')} key={v[0]}><b>{v[0]}</b><p className="mt-1 text-xs text-slate-500">{v[1]} · {v[2]}</p><p className="mt-3 text-sm">{v[3]}</p></article>)}</div><div className="mt-5 rounded-xl border"><div className="grid grid-cols-2 border-b bg-slate-50 text-xs font-bold"><span className="p-3">Versi 1</span><span className="border-l p-3">Versi 2</span></div><div className="grid grid-cols-2 text-sm"><p className="bg-rose-50 p-4 line-through">Amlodipine 10 mg</p><p className="border-l bg-emerald-50 p-4 font-semibold">Amlodipine 5 mg</p></div></div><p className="mt-4 text-xs text-slate-500">Seluruh perubahan, waktu, identitas pengguna, dan alasan tersimpan dalam audit trail.</p></div></Modal>}
function PrintModal({data,bmi,whtr,onClose}:{data:FormData;bmi:string;whtr:string;onClose:()=>void}){return <Modal title="Print preview" onClose={onClose} wide><div className="bg-slate-100 p-6"><article className="mx-auto max-w-2xl bg-white p-8 shadow"><div className="flex justify-between border-b pb-4"><div><b className="text-xl">SINAESTA</b><p className="text-xs">Puskesmas Sukamaju</p></div><div className="text-right text-xs"><b>CATATAN PEMERIKSAAN</b><p>#KJ-2026-0807-014</p></div></div><h3 className="mt-5 font-bold">Siti Aminah · RM-2026-001284</h3>{[['SUBJECTIVE',data.chiefComplaint+' '+data.presentIllness],['OBJECTIVE',`TD ${data.systolic}/${data.diastolic} mmHg · Nadi ${data.pulse} · IMT ${bmi} · WtH ${whtr}. ${data.physicalExam}`],['ASSESSMENT',data.workingDiagnosis+(data.differentialDiagnosis?` · DD: ${data.differentialDiagnosis}`:'')],['PLAN',data.therapyPlan+' '+data.education]].map(([a,b])=>b&&<section className="mt-5" key={a}><b className="text-xs tracking-widest text-brand">{a}</b><p className="mt-1 whitespace-pre-wrap text-sm leading-6">{b}</p></section>)}</article></div><footer className="flex justify-end gap-2 border-t p-4"><button className="btn-secondary" onClick={()=>window.print()}><Printer size={16}/> Cetak</button><button className="btn-primary" onClick={()=>window.print()}><FileDown size={16}/> Ekspor PDF</button></footer></Modal>}
function CopyModal({onClose,onCopy}:{onClose:()=>void;onCopy:()=>void}){const [chosen,setChosen]=useState(['Riwayat penyakit dahulu','Riwayat obat','Riwayat alergi']);return <Modal title="Salin dari kunjungan sebelumnya" onClose={onClose}><div className="p-5"><p className="text-sm text-slate-500">Pilih hanya data yang masih relevan. Data tidak pernah disalin otomatis.</p><div className="mt-4 space-y-2">{['Riwayat penyakit dahulu','Riwayat obat','Riwayat alergi','Riwayat keluarga','Pemeriksaan fisik','Diagnosis'].map(x=><label className="flex items-center gap-3 rounded-xl border p-3 text-sm font-semibold" key={x}><input type="checkbox" checked={chosen.includes(x)} onChange={()=>setChosen(chosen.includes(x)?chosen.filter(c=>c!==x):[...chosen,x])}/>{x}</label>)}</div><button className="btn-primary mt-5 w-full" onClick={onCopy}>Salin {chosen.length} bagian terpilih</button></div></Modal>}
function Addendum({onClose,onSave}:{onClose:()=>void;onSave:()=>void}){const [reason,setReason]=useState('');const [content,setContent]=useState('');return <Modal title="Addendum catatan terkunci" onClose={onClose}><div className="p-5"><div className="rounded-xl bg-violet-50 p-3 text-sm text-violet-800"><LockKeyhole className="mr-2 inline" size={16}/>Catatan asli tetap utuh dan dapat dibandingkan.</div><label className="mt-4 block"><span className="label">Alasan koreksi <span className="text-rose-600">*</span></span><input className="field" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Jelaskan alasan addendum"/></label><label className="mt-4 block"><span className="label">Isi addendum <span className="text-rose-600">*</span></span><textarea className="field min-h-28 py-3" value={content} onChange={e=>setContent(e.target.value)}/></label><div className="mt-4 rounded-xl border p-3 text-xs text-slate-500"><Clock3 className="mr-2 inline" size={15}/>7 Agustus 2026, 10.48 · dr. Ayu Santoso</div><button className="btn-primary mt-5 w-full" disabled={!reason.trim()||!content.trim()} onClick={onSave}>Tanda tangani & simpan addendum</button></div></Modal>}
