import { Link } from '@tanstack/react-router'
import { AlertTriangle, ArrowLeft, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Copy, Download, Eye, EyeOff, FileText, Filter, HeartPulse, History, MapPin, Merge, MoreHorizontal, Plus, Save, Search, ShieldAlert, ShieldCheck, SlidersHorizontal, UserRound, X } from 'lucide-react'
import { useMemo, useState, type ReactNode } from 'react'
import { useToast } from '@/components/ui'
import { cn } from '@/lib/utils'

type Patient={id:string;name:string;initials:string;mrn:string;nik:string;birth:string;age:number;gender:'Laki-laki'|'Perempuan';phone:string;area:string;facility:string;lastVisit:string;risk:'Tinggi'|'Sedang'|'Rendah';active:boolean;conditions:string[];color:string}
const patients:Patient[]=[
 {id:'pt-001',name:'Siti Aminah',initials:'SA',mrn:'RM-2026-001284',nik:'3273••••••••0012',birth:'12 Mei 1968',age:58,gender:'Perempuan',phone:'0812 •••• 4421',area:'Kel. Sukamaju, Kec. Cibeunying',facility:'Puskesmas Sukamaju',lastVisit:'05 Agu 2026',risk:'Tinggi',active:true,conditions:['Diabetes','Hipertensi'],color:'bg-rose-100 text-rose-700'},
 {id:'pt-002',name:'Budi Hartono',initials:'BH',mrn:'RM-2025-000892',nik:'3273••••••••0294',birth:'21 Januari 1982',age:44,gender:'Laki-laki',phone:'0857 •••• 9910',area:'Kel. Cikutra, Kec. Cibeunying',facility:'Klinik Pratama Sehat',lastVisit:'02 Agu 2026',risk:'Sedang',active:true,conditions:['Asma'],color:'bg-blue-100 text-blue-700'},
 {id:'pt-003',name:'Dewi Lestari',initials:'DL',mrn:'RM-2026-001102',nik:'3273••••••••1138',birth:'07 September 1994',age:31,gender:'Perempuan',phone:'0821 •••• 0177',area:'Kel. Antapani Kidul, Kec. Antapani',facility:'Puskesmas Sukamaju',lastVisit:'28 Jul 2026',risk:'Rendah',active:true,conditions:[],color:'bg-violet-100 text-violet-700'},
 {id:'pt-004',name:'Ahmad Fauzi',initials:'AF',mrn:'RM-2024-000431',nik:'3273••••••••7641',birth:'18 Maret 1954',age:72,gender:'Laki-laki',phone:'0813 •••• 2388',area:'Kel. Sukamiskin, Kec. Arcamanik',facility:'RSUD Kota Bandung',lastVisit:'14 Jun 2026',risk:'Tinggi',active:false,conditions:['Jantung','Hipertensi'],color:'bg-amber-100 text-amber-700'},
]
const riskStyle={Tinggi:'bg-rose-50 text-rose-700 ring-rose-200',Sedang:'bg-amber-50 text-amber-700 ring-amber-200',Rendah:'bg-emerald-50 text-emerald-700 ring-emerald-200'}

function Risk({value}:{value:Patient['risk']}){return <span className={cn('inline-flex rounded-full px-2.5 py-1 text-xs font-bold ring-1',riskStyle[value])}>{value}</span>}
function FilterSelect({label,children}:{label:string;children?:ReactNode}){return <label><span className="sr-only">{label}</span><select className="field min-w-36" defaultValue=""><option value="">{label}</option>{children}</select></label>}

export function Patients(){
 const [query,setQuery]=useState('');const [filters,setFilters]=useState(true);const [saved,setSaved]=useState(false);const toast=useToast()
 const result=useMemo(()=>patients.filter(p=>(p.name+' '+p.mrn).toLowerCase().includes(query.toLowerCase())),[query])
 return <>
  <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-sm text-slate-500"><span>Master Data</span><ChevronRight size={14}/><span className="text-ink">Pasien</span></div><h1 className="mt-2 text-3xl font-black">Daftar Pasien</h1><p className="mt-1 text-sm text-slate-500">Kelola identitas pasien secara aman dan terpusat.</p></div><Link to="/app/patients/new" className="btn-primary"><Plus size={18}/> Tambah pasien</Link></div>
  <section className="mt-6 rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 lg:flex-row"><label className="relative flex-1"><span className="sr-only">Cari pasien</span><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input className="field pl-10" placeholder="Cari nama atau nomor rekam medis..." value={query} onChange={e=>setQuery(e.target.value)}/></label><button className={cn('btn-secondary justify-start',filters&&'border-brand bg-teal-50 text-brand')} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={17}/> Filter <span className="grid h-5 w-5 place-items-center rounded-full bg-brand text-[11px] text-white">2</span></button><button className="btn-secondary justify-start" onClick={()=>setSaved(!saved)}><Save size={17}/> Filter tersimpan</button></div>
   {saved&&<div className="border-b bg-slate-50 p-4"><p className="mb-3 text-xs font-bold uppercase tracking-wider text-slate-500">Filter tersimpan</p><div className="flex flex-wrap gap-2"><button className="chip" onClick={()=>toast('Filter “Pasien risiko tinggi” diterapkan')}>Pasien risiko tinggi</button><button className="chip" onClick={()=>toast('Filter “Kunjungan bulan ini” diterapkan')}>Kunjungan bulan ini</button><button className="chip" onClick={()=>toast('Filter “Lansia Sukamaju” diterapkan')}>Lansia Sukamaju</button></div></div>}
   {filters&&<div className="border-b bg-slate-50/70 p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7"><FilterSelect label="Semua fasilitas"><option>Puskesmas Sukamaju</option><option>Klinik Pratama Sehat</option></FilterSelect><FilterSelect label="Semua wilayah"><option>Cibeunying</option><option>Antapani</option></FilterSelect><FilterSelect label="Kelompok usia"><option>Balita (0–5)</option><option>Dewasa (18–59)</option><option>Lansia (60+)</option></FilterSelect><FilterSelect label="Jenis kelamin"><option>Laki-laki</option><option>Perempuan</option></FilterSelect><FilterSelect label="Status aktif"><option>Aktif</option><option>Nonaktif</option></FilterSelect><FilterSelect label="Risiko kesehatan"><option>Tinggi</option><option>Sedang</option><option>Rendah</option></FilterSelect><label><span className="sr-only">Tanggal kunjungan terakhir</span><input type="date" className="field" title="Kunjungan sejak"/></label></div><div className="mt-3 flex items-center justify-between"><button className="text-sm font-bold text-slate-500">Reset filter</button><button className="text-sm font-bold text-brand" onClick={()=>toast('Kombinasi filter berhasil disimpan')}><Plus size={15} className="inline"/> Simpan filter ini</button></div></div>}
   <div className="hidden overflow-x-auto md:block"><table className="w-full text-left"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Pasien</th><th className="px-5 py-3">Kontak & wilayah</th><th className="px-5 py-3">Fasilitas utama</th><th className="px-5 py-3">Kunjungan terakhir</th><th className="px-5 py-3">Risiko</th><th className="px-5 py-3"><span className="sr-only">Aksi</span></th></tr></thead><tbody className="divide-y">{result.map(p=><tr key={p.id} className="hover:bg-slate-50"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className={cn('grid h-10 w-10 shrink-0 place-items-center rounded-full text-xs font-black',p.color)}>{p.initials}</span><div><Link to="/app/patients/$patientId" params={{patientId:p.id}} className="font-bold hover:text-brand">{p.name}</Link><p className="mt-0.5 text-xs text-slate-500">{p.mrn} · {p.gender==='Laki-laki'?'L':'P'}, {p.age} th</p></div></div></td><td className="px-5 py-4 text-sm"><p>{p.phone}</p><p className="mt-1 max-w-48 truncate text-xs text-slate-500">{p.area}</p></td><td className="px-5 py-4 text-sm">{p.facility}</td><td className="px-5 py-4 text-sm"><b>{p.lastVisit}</b><p className="mt-1 text-xs text-slate-500">Rawat jalan</p></td><td className="px-5 py-4"><Risk value={p.risk}/></td><td className="px-5 py-4"><button aria-label={`Aksi ${p.name}`} className="rounded-lg p-2 hover:bg-slate-100"><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table></div>
   <div className="divide-y md:hidden">{result.map(p=><article className="p-4" key={p.id}><div className="flex gap-3"><span className={cn('grid h-11 w-11 shrink-0 place-items-center rounded-full text-xs font-black',p.color)}>{p.initials}</span><div className="min-w-0 flex-1"><Link to="/app/patients/$patientId" params={{patientId:p.id}} className="font-bold">{p.name}</Link><p className="text-xs text-slate-500">{p.mrn}</p></div><Risk value={p.risk}/></div><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-500">Usia / JK</dt><dd className="mt-1 font-semibold">{p.age} tahun · {p.gender}</dd></div><div><dt className="text-slate-500">Kunjungan terakhir</dt><dd className="mt-1 font-semibold">{p.lastVisit}</dd></div><div className="col-span-2"><dt className="text-slate-500">Fasilitas utama</dt><dd className="mt-1 font-semibold">{p.facility}</dd></div></dl></article>)}</div>
   <div className="flex flex-col gap-3 border-t p-4 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>Menampilkan <b className="text-ink">1–{result.length}</b> dari <b className="text-ink">1.284</b> pasien</p><div className="flex items-center gap-1"><button className="btn-secondary min-h-9 px-3" disabled><ChevronLeft size={16}/></button>{[1,2,3].map(n=><button key={n} className={cn('grid h-9 w-9 place-items-center rounded-lg font-bold',n===1?'bg-brand text-white':'hover:bg-slate-100')}>{n}</button>)}<span>…</span><button className="grid h-9 w-9 place-items-center rounded-lg font-bold hover:bg-slate-100">128</button><button className="btn-secondary min-h-9 px-3"><ChevronRight size={16}/></button></div></div>
  </section>
 </>
}

const fieldGroups=[
 {title:'Identitas pasien',desc:'Data utama untuk identifikasi pasien.',fields:[['Nomor rekam medis internal','RM-2026-001285'],['NIK','Masukkan 16 digit NIK'],['Nama lengkap','Sesuai dokumen identitas'],['Tanggal lahir','date'],['Jenis kelamin','select:jenis_kelamin'],['Nomor telepon','08xx xxxx xxxx'],['Email','nama@email.com']]},
 {title:'Alamat & demografi',desc:'Domisili dan informasi sosial pasien.',fields:[['Alamat','Nama jalan, nomor rumah'],['RT','000'],['RW','000'],['Desa / Kelurahan','Pilih kelurahan'],['Kecamatan','Pilih kecamatan'],['Kota / Kabupaten','Pilih kota atau kabupaten'],['Koordinat lokasi (opsional)','-6.9175, 107.6191'],['Pekerjaan','Pilih pekerjaan'],['Pendidikan','select:pendidikan'],['Status perkawinan','select:perkawinan']]},
 {title:'Kontak & penanggung jawab',desc:'Pihak yang dapat dihubungi saat diperlukan.',fields:[['Penanggung jawab','Nama penanggung jawab'],['Hubungan dengan pasien','Pilih hubungan'],['Nomor telepon penanggung jawab','08xx xxxx xxxx'],['Kontak darurat','Nama kontak darurat'],['Nomor kontak darurat','08xx xxxx xxxx']]},
 {title:'Informasi pelayanan',desc:'Fasilitas, klinisi, dan ringkasan kesehatan.',fields:[['Fasilitas pelayanan utama','select:fasilitas'],['Dokter penanggung jawab','select:dokter'],['Alergi','Contoh: penisilin, kacang'],['Kondisi kronis','Contoh: diabetes, hipertensi'],['Status kepesertaan pembiayaan','select:pembiayaan'],['Tanggal kunjungan terakhir','date']]},
]
function Field({label,hint}:{label:string;hint:string}){const isSelect=hint.startsWith('select:');return <label className={cn(label==='Alamat'&&'sm:col-span-2')}><span className="label">{label}{['NIK','Nama lengkap','Tanggal lahir','Jenis kelamin'].includes(label)&&<span className="text-rose-500"> *</span>}</span>{isSelect?<select className="field" defaultValue=""><option value="" disabled>{label}</option><option>Belum ditentukan</option></select>:<div className="relative"><input className="field" type={hint==='date'?'date':'text'} placeholder={hint}/>{label==='NIK'&&<EyeOff className="absolute right-3 top-3 text-slate-400" size={17}/>}</div>}{label==='Tanggal lahir'&&<p className="mt-1 text-xs text-slate-500">Usia dihitung otomatis setelah tanggal dipilih.</p>}</label>}
export function PatientForm(){const [duplicate,setDuplicate]=useState(false);const toast=useToast();return <><div className="flex items-center gap-3"><Link to="/app/patients" className="grid h-10 w-10 place-items-center rounded-xl border bg-white" aria-label="Kembali"><ArrowLeft size={18}/></Link><div><p className="text-sm text-slate-500">Pasien / Tambah pasien</p><h1 className="text-2xl font-black">Pasien baru</h1></div></div><form className="mt-6 grid gap-6 xl:grid-cols-[1fr_280px]" onSubmit={e=>{e.preventDefault();setDuplicate(true)}}><div className="space-y-5">{fieldGroups.map(group=><section className="card" key={group.title}><div className="border-b pb-4"><h2 className="text-lg font-bold">{group.title}</h2><p className="mt-1 text-sm text-slate-500">{group.desc}</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{group.fields.map(([label,hint])=><Field key={label} label={label} hint={hint}/>)}</div></section>)}</div><aside><div className="card sticky top-20"><ShieldCheck className="text-brand"/><h2 className="mt-3 font-bold">Perlindungan data</h2><p className="mt-2 text-xs leading-5 text-slate-500">NIK dan data pribadi akan dienkripsi. Akses dan perubahan dicatat dalam riwayat audit.</p><div className="my-5 border-t"/><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Kelengkapan data</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-1/4 bg-brand"/></div><p className="mt-2 text-xs text-slate-500">6 dari 24 data wajib terisi</p><button className="btn-primary mt-6 w-full" type="submit"><Save size={17}/> Simpan pasien</button><Link to="/app/patients" className="btn-secondary mt-2 w-full">Batal</Link></div></aside></form>{duplicate&&<DuplicateDialog onClose={()=>setDuplicate(false)} onSave={()=>{setDuplicate(false);toast('Data pasien tersimpan sebagai pasien baru')}}/>}</>}

function DuplicateDialog({onClose,onSave}:{onClose:()=>void;onSave:()=>void}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><section role="dialog" aria-modal="true" aria-labelledby="duplicate-title" className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded-2xl bg-white shadow-2xl"><header className="flex items-start justify-between border-b p-5"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-100 text-amber-700"><Copy size={20}/></span><div><h2 id="duplicate-title" className="text-lg font-bold">Kemungkinan pasien duplikat ditemukan</h2><p className="mt-1 text-sm text-slate-500">Periksa perbandingan data sebelum melanjutkan. Sistem tidak akan menggabungkan data otomatis.</p></div></div><button onClick={onClose} aria-label="Tutup"><X/></button></header><div className="p-5"><div className="mb-4 flex items-center gap-2 rounded-xl bg-amber-50 p-3 text-sm text-amber-800"><AlertTriangle size={18}/><b>Tingkat kecocokan 92%</b><span>· NIK, nama, dan tanggal lahir serupa</span></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-3 text-left text-slate-500">Data</th><th className="p-3 text-left">Pasien baru</th><th className="p-3 text-left">Pasien terdaftar</th></tr></thead><tbody className="divide-y">{[['NIK','3273••••••••0012','3273••••••••0012'],['Nama','Siti Aminah','Siti Aminah'],['Tanggal lahir','12 Mei 1968','12 Mei 1968'],['Telepon','0812 •••• 4421','0812 •••• 4471'],['Alamat','Jl. Melati No. 12, Sukamaju','Jl. Melati 12, Sukamaju']].map(([a,b,c],i)=><tr key={a} className={i<3?'bg-amber-50/50':''}><th className="p-3 text-left text-slate-500">{a}</th><td className="p-3 font-semibold">{b}</td><td className="p-3 font-semibold">{c}{i<3&&<Check className="ml-2 inline text-emerald-600" size={15}/>}</td></tr>)}</tbody></table></div></div><footer className="flex flex-col-reverse gap-2 border-t p-5 sm:flex-row sm:justify-end"><button className="btn-secondary" onClick={onSave}>Tetap buat pasien baru</button><Link to="/app/patients/$patientId" params={{patientId:'pt-001'}} className="btn-primary"><Eye size={17}/> Tinjau pasien terdaftar</Link></footer></section></div>}

const tabs=['Ringkasan','Timeline klinis','Pemeriksaan','Obat','Alergi','Skrining','Konsultasi','Rujukan','Dokumen','Persetujuan','Riwayat akses']
export function PatientDetail(){const [tab,setTab]=useState('Ringkasan');const [nik,setNik]=useState(false);const [breakGlass,setBreakGlass]=useState(false);return <><Link to="/app/patients" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-brand"><ArrowLeft size={16}/> Daftar pasien</Link><section className="mt-4 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-4"><span className="grid h-16 w-16 shrink-0 place-items-center rounded-2xl bg-rose-100 text-lg font-black text-rose-700">SA</span><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-black">Siti Aminah</h1><span className="chip bg-emerald-50 text-emerald-700">Aktif</span><Risk value="Tinggi"/></div><p className="mt-1 text-sm text-slate-500">RM-2026-001284 · Perempuan, 58 tahun · Puskesmas Sukamaju</p><button className="mt-2 flex items-center gap-2 text-xs text-slate-500" onClick={()=>setNik(!nik)}>{nik?'3273015205680012':'NIK 3273••••••••0012'} {nik?<EyeOff size={14}/>:<Eye size={14}/>}</button></div></div><div className="flex flex-wrap gap-2"><button className="btn border-rose-200 bg-rose-50 text-rose-700" onClick={()=>setBreakGlass(true)}><ShieldAlert size={17}/> Break Glass Access</button><button className="btn-secondary">Edit pasien</button><button className="btn-secondary px-3" aria-label="Aksi lainnya"><MoreHorizontal/></button></div></div><div className="mt-5 flex gap-1 overflow-x-auto border-t pt-4" role="tablist" aria-label="Informasi pasien">{tabs.map(t=><button role="tab" aria-selected={tab===t} onClick={()=>setTab(t)} key={t} className={cn('shrink-0 rounded-lg px-3 py-2 text-sm font-semibold',tab===t?'bg-brand text-white':'text-slate-500 hover:bg-slate-50')}>{t}</button>)}</div></section><div className="mt-5">{tab==='Ringkasan'?<Summary/>:tab==='Persetujuan'?<Consents/>:tab==='Riwayat akses'?<AccessHistory/>:<EmptyTab title={tab}/>}</div>{breakGlass&&<BreakGlass onClose={()=>setBreakGlass(false)}/>}</>}

function Summary(){return <div className="grid gap-5 lg:grid-cols-3"><div className="space-y-5 lg:col-span-2"><section className="card"><div className="flex items-center justify-between"><div><p className="eyebrow">Perhatian klinis</p><h2 className="mt-1 text-lg font-bold">Risiko & kondisi aktif</h2></div><HeartPulse className="text-rose-500"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-rose-200 bg-rose-50 p-4"><b className="text-sm text-rose-800">Alergi obat</b><p className="mt-1 text-sm text-rose-700">Penisilin · Reaksi berat</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><b className="text-sm text-amber-800">Kondisi kronis</b><p className="mt-1 text-sm text-amber-700">Diabetes tipe 2, Hipertensi</p></div></div></section><section className="card"><div className="flex justify-between"><div><p className="eyebrow">Aktivitas terbaru</p><h2 className="mt-1 text-lg font-bold">Timeline klinis</h2></div><button className="text-sm font-bold text-brand">Lihat semua</button></div><div className="mt-5 space-y-5">{[['05 Agu 2026','Kunjungan rawat jalan','Kontrol diabetes · dr. Ayu Santoso'],['19 Jul 2026','Hasil pemeriksaan','HbA1c 7,2% · Laboratorium'],['02 Jul 2026','Resep obat','Metformin 500 mg · 30 tablet']].map(([d,t,s],i)=><div className="relative flex gap-4" key={t}><span className={cn('mt-1 grid h-9 w-9 shrink-0 place-items-center rounded-full',i===0?'bg-brand text-white':'bg-mist text-brand')}>{i===0?<CalendarDays size={16}/>:<FileText size={16}/>}</span><div><p className="text-xs text-slate-500">{d}</p><b className="text-sm">{t}</b><p className="text-sm text-slate-500">{s}</p></div></div>)}</div></section></div><aside className="space-y-5"><section className="card"><h2 className="font-bold">Informasi pasien</h2><dl className="mt-4 space-y-4 text-sm">{[['Telepon','0812 •••• 4421'],['Email','s•••@email.com'],['Alamat','Kel. Sukamaju, Kec. Cibeunying'],['Pembiayaan','JKN · Aktif'],['Dokter PJ','dr. Ayu Santoso']].map(([a,b])=><div key={a}><dt className="text-xs text-slate-500">{a}</dt><dd className="mt-1 font-semibold">{b}</dd></div>)}</dl></section><section className="card"><h2 className="font-bold">Kunjungan berikutnya</h2><div className="mt-4 flex gap-3"><CalendarDays className="text-brand"/><div><b className="text-sm">12 Agustus 2026</b><p className="text-xs text-slate-500">09.30 WIB · Poli penyakit dalam</p></div></div></section></aside></div>}
function EmptyTab({title}:{title:string}){return <section className="card py-14 text-center"><FileText className="mx-auto text-slate-300" size={38}/><h2 className="mt-4 font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">Data {title.toLowerCase()} pasien akan ditampilkan di sini.</p><button className="btn-primary mt-5"><Plus size={17}/> Tambah data</button></section>}

function Consents(){const toast=useToast();return <section className="card"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">Privasi pasien</p><h2 className="mt-1 text-xl font-bold">Persetujuan pemrosesan data</h2><p className="mt-1 text-sm text-slate-500">Dokumentasi persetujuan dan status masa berlakunya.</p></div><button className="btn-primary" onClick={()=>toast('Form persetujuan baru dibuka')}><Plus size={17}/> Catat persetujuan</button></div><div className="mt-5 grid gap-4 md:grid-cols-2"><article className="rounded-xl border p-4"><div className="flex justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><ShieldCheck size={20}/></span><span className="chip bg-emerald-50 text-emerald-700">Aktif</span></div><h3 className="mt-4 font-bold">Pelayanan dan rekam medis</h3><p className="mt-1 text-sm text-slate-500">Tujuan: Pelayanan kesehatan dan kesinambungan perawatan.</p><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-500">Versi dokumen</dt><dd className="font-semibold">v2.1</dd></div><div><dt className="text-slate-500">Diberikan oleh</dt><dd className="font-semibold">Pasien sendiri</dd></div><div><dt className="text-slate-500">Tanggal & cara</dt><dd className="font-semibold">05 Agu 2026, 09.14 · Digital</dd></div><div><dt className="text-slate-500">Berlaku hingga</dt><dd className="font-semibold">05 Agu 2027</dd></div></dl><button className="btn-secondary mt-4 w-full"><Download size={16}/> Lihat bukti persetujuan</button></article><article className="rounded-xl border p-4"><div className="flex justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-slate-500"><History size={20}/></span><span className="chip bg-slate-100 text-slate-600">Ditarik</span></div><h3 className="mt-4 font-bold">Riset kesehatan populasi</h3><p className="mt-1 text-sm text-slate-500">Tujuan: Analisis data terdeidentifikasi untuk riset.</p><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-500">Versi dokumen</dt><dd className="font-semibold">v1.3</dd></div><div><dt className="text-slate-500">Diberikan oleh</dt><dd className="font-semibold">Pasien sendiri</dd></div><div><dt className="text-slate-500">Diperoleh</dt><dd className="font-semibold">12 Jan 2026 · Tertulis</dd></div><div><dt className="text-slate-500">Ditarik pada</dt><dd className="font-semibold">20 Jul 2026, 14.22</dd></div></dl></article></div></section>}
function AccessHistory(){return <section className="card"><h2 className="text-xl font-bold">Riwayat akses</h2><p className="mt-1 text-sm text-slate-500">Seluruh akses terhadap data sensitif pasien tercatat.</p><div className="mt-5 divide-y">{[['Hari ini, 10.42','dr. Ayu Santoso','Melihat ringkasan pasien','Akses rutin'],['05 Agu 2026, 09.17','Nia Rahmawati, Perawat','Memperbarui hasil pemeriksaan','Akses rutin'],['21 Jul 2026, 22.08','dr. Rangga Putra','Membuka data alergi dan obat','Break Glass · IGD']].map(([a,b,c,d])=><div className="grid gap-1 py-4 text-sm md:grid-cols-[180px_220px_1fr_auto]" key={a}><span className="text-slate-500">{a}</span><b>{b}</b><span>{c}</span><span className={cn('chip w-fit',d.startsWith('Break')&&'bg-rose-50 text-rose-700')}>{d}</span></div>)}</div></section>}

function BreakGlass({onClose}:{onClose:()=>void}){const [reason,setReason]=useState('');const [done,setDone]=useState(false);return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><section role="alertdialog" aria-modal="true" aria-labelledby="break-title" className="w-full max-w-lg rounded-2xl bg-white shadow-2xl"><header className="rounded-t-2xl bg-rose-700 p-5 text-white"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-white/15"><ShieldAlert/></span><button onClick={onClose} aria-label="Tutup"><X/></button></div><h2 id="break-title" className="mt-4 text-xl font-black">Break Glass Access</h2><p className="mt-1 text-sm text-white/80">Akses darurat ke data pasien yang dibatasi.</p></header>{done?<div className="p-6 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-emerald-100 text-emerald-700"><Check/></span><h3 className="mt-4 text-lg font-bold">Akses darurat diberikan</h3><p className="mt-2 text-sm text-slate-500">Akses berlaku selama 30 menit. Administrator telah diberi notifikasi dan seluruh aktivitas Anda akan dicatat.</p><button className="btn-primary mt-6 w-full" onClick={onClose}>Lanjutkan ke data pasien</button></div>:<div className="p-5"><div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800"><b>Gunakan hanya dalam kondisi darurat.</b><p className="mt-1 text-xs">Penyalahgunaan akses dapat dikenai tindakan disipliner.</p></div><label className="mt-5 block"><span className="label">Alasan akses darurat <span className="text-rose-600">*</span></span><textarea className="field min-h-28 py-3" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Jelaskan kondisi darurat dan data yang dibutuhkan..."/></label><div className="mt-4 flex items-center gap-3 rounded-xl bg-slate-50 p-3"><Clock3 className="text-slate-500"/><div><b className="text-sm">Durasi akses: 30 menit</b><p className="text-xs text-slate-500">Akses berakhir otomatis pada 11.30 WIB</p></div></div><div className="mt-5 flex gap-2"><button className="btn-secondary flex-1" onClick={onClose}>Batal</button><button className="btn flex-1 bg-rose-700 text-white hover:bg-rose-800" disabled={reason.trim().length<10} onClick={()=>setDone(true)}><ShieldAlert size={17}/> Berikan akses</button></div></div>}</section></div>}
