import { CheckCircle2, Clock3, MailPlus, MoreHorizontal, Search, ShieldCheck, UserRoundCheck, UserRoundX } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useToast } from '@/components/ui'

type Member={name:string;initials:string;email:string;profession:string;facility:string;role:string;status:'Aktif'|'Diundang'|'Nonaktif';credential:'Terverifikasi'|'Menunggu'|'Kedaluwarsa';lastActive:string}
const members:Member[]=[
  {name:'dr. Maya Putri, Sp.PD',initials:'MP',email:'maya.putri@sinaesta.id',profession:'Dokter',facility:'RS SINAESTA Utama',role:'Dokter',status:'Aktif',credential:'Terverifikasi',lastActive:'2 menit lalu'},
  {name:'Ns. Aditya Pratama',initials:'AP',email:'aditya.pratama@sinaesta.id',profession:'Perawat',facility:'RS SINAESTA Utama',role:'Perawat',status:'Aktif',credential:'Terverifikasi',lastActive:'18 menit lalu'},
  {name:'drg. Nadia Rahman',initials:'NR',email:'nadia.rahman@sinaesta.id',profession:'Dokter Gigi',facility:'Klinik SINAESTA Barat',role:'Dokter Gigi',status:'Diundang',credential:'Menunggu',lastActive:'Belum pernah'},
  {name:'Siti Aminah, A.Md.Keb',initials:'SA',email:'siti.aminah@sinaesta.id',profession:'Bidan',facility:'Klinik SINAESTA Barat',role:'Bidan',status:'Nonaktif',credential:'Kedaluwarsa',lastActive:'31 Jul 2026'},
]
const badge=(value:string)=>value==='Aktif'||value==='Terverifikasi'?'bg-emerald-50 text-emerald-700':value==='Nonaktif'||value==='Kedaluwarsa'?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700'

export function UserManagement(){
  const toast=useToast(),[query,setQuery]=useState(''),[status,setStatus]=useState('Semua status')
  const filtered=useMemo(()=>members.filter(m=>(status==='Semua status'||m.status===status)&&`${m.name} ${m.email} ${m.profession} ${m.facility}`.toLowerCase().includes(query.toLowerCase())),[query,status])
  return <><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Akses & organisasi</p><h1 className="mt-2 text-3xl font-black">Manajemen Pengguna</h1><p className="mt-2 text-sm text-slate-500">Kelola anggota, peran, dan kredensial di fasilitas aktif.</p></div><button className="btn-primary" onClick={()=>toast('Formulir undangan dibuka.')}><MailPlus size={17}/> Undang anggota</button></div>
  <section className="mt-7 grid gap-4 sm:grid-cols-3"><Summary icon={<UserRoundCheck/>} label="Pengguna aktif" value="128" note="dari 142 anggota"/><Summary icon={<Clock3/>} label="Menunggu undangan" value="8" note="3 akan kedaluwarsa"/><Summary icon={<ShieldCheck/>} label="Kredensial perlu ditinjau" value="6" note="2 telah kedaluwarsa"/></section>
  <section className="card mt-6 p-0"><div className="flex flex-col gap-3 border-b p-4 md:flex-row"><label className="relative flex-1"><span className="sr-only">Cari pengguna</span><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className="field pl-10" placeholder="Cari nama, email, profesi, atau fasilitas…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select className="field md:w-48" value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filter status">{['Semua status','Aktif','Diundang','Nonaktif'].map(x=><option key={x}>{x}</option>)}</select></div>
  <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{['Pengguna','Profesi & fasilitas','Peran','Status','Terakhir aktif','Kredensial',''].map(x=><th className="whitespace-nowrap px-5 py-4" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{filtered.map(m=><tr className="hover:bg-mist" key={m.email}><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-brand/10 font-bold text-brand">{m.initials}</span><div><b className="whitespace-nowrap">{m.name}</b><p className="text-xs text-slate-500">{m.email}</p></div></div></td><td className="whitespace-nowrap px-5 py-4"><b>{m.profession}</b><p className="text-xs text-slate-500">{m.facility}</p></td><td className="px-5 py-4"><span className="chip">{m.role}</span></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${badge(m.status)}`}>{m.status}</span></td><td className="whitespace-nowrap px-5 py-4 text-slate-600">{m.lastActive}</td><td className="px-5 py-4"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-bold ${badge(m.credential)}`}><CheckCircle2 size={13}/>{m.credential}</span></td><td className="px-5 py-4"><button aria-label={`Aksi untuk ${m.name}`} className="rounded-lg p-2 hover:bg-slate-100" onClick={()=>toast(`Menu ${m.name} dibuka.`)}><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table>{filtered.length===0&&<div className="p-10 text-center text-sm text-slate-500"><UserRoundX className="mx-auto mb-3"/>Tidak ada pengguna yang cocok.</div>}</div><div className="border-t p-4 text-xs text-slate-500">Menampilkan {filtered.length} dari 142 pengguna · Perubahan akses tercatat otomatis di audit log.</div></section></>
}
function Summary({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <article className="card"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-brand/10 text-brand">{icon}</span><strong className="text-2xl">{value}</strong></div><h2 className="mt-4 font-bold">{label}</h2><p className="text-xs text-slate-500">{note}</p></article>}
