import { Link, Outlet, useRouterState } from '@tanstack/react-router'
import { BarChart3, BookOpenCheck, ChevronDown, CircleDollarSign, ClipboardList, FileQuestion, History, Home, Menu, Package, Settings, ShieldCheck, Ticket, Trophy, Users, X } from 'lucide-react'
import { useState } from 'react'
import { cn } from '@/lib/utils'

export function PublicHeader(){const [open,setOpen]=useState(false);return <header className="sticky top-0 z-40 border-b bg-white/90 backdrop-blur"><div className="container-app flex h-16 items-center justify-between"><Link to="/" className="text-xl font-black tracking-tight">SINA<span className="text-brand">ESTA</span></Link><button className="md:hidden" aria-expanded={open} aria-label="Buka navigasi" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav aria-label="Navigasi utama" className={cn('items-center gap-7 text-sm font-semibold',open?'absolute left-0 top-16 flex w-full flex-col border-b bg-white p-6':'hidden md:flex')}><Link to="/pricing">Paket ujian</Link><Link to="/faq">FAQ</Link><Link to="/login">Masuk</Link><Link to="/register" className="btn-primary">Mulai gratis</Link></nav></div></header>}
const appNav=[['/app/dashboard','Dashboard',Home],['/app/exams','Ujian & kuis',ClipboardList],['/app/history','Riwayat ujian',History],['/app/analytics','Analisis hasil',BarChart3],['/app/leaderboard','Ranking',Trophy],['/app/packages','Paket & token',Package],['/app/transactions','Pembayaran',CircleDollarSign],['/app/settings','Pengaturan',Settings]] as const
const adminNav=[['dashboard','Dashboard',Home],['exams','Kelola ujian',ClipboardList],['questions','Bank soal',FileQuestion],['question-pools','Question pool',BookOpenCheck],['attempts','Monitoring attempt',Users],['results','Hasil & ekspor',BarChart3],['packages','Paket & token',Ticket],['transactions','Pembayaran',CircleDollarSign],['audit','Audit & keamanan',ShieldCheck]] as const
export function AppLayout({admin=false}:{admin?:boolean}){const [open,setOpen]=useState(false);const path=useRouterState({select:s=>s.location.pathname});const nav=admin?adminNav.map(([slug,label,Icon])=>[`/admin/${slug}`,label,Icon] as const):appNav;return <div className="min-h-screen bg-mist"><aside className={cn('fixed inset-y-0 left-0 z-40 w-64 overflow-y-auto border-r bg-white p-4 transition-transform lg:translate-x-0',open?'translate-x-0':'-translate-x-full')}><div className="mb-8 flex items-center justify-between px-2"><Link to={admin?'/admin/dashboard':'/app/dashboard'} className="text-xl font-black">SINA<span className="text-brand">ESTA</span></Link><button aria-label="Tutup menu" className="lg:hidden" onClick={()=>setOpen(false)}><X/></button></div><nav aria-label={admin?'Navigasi admin':'Navigasi peserta'} className="space-y-1">{nav.map(([to,label,Icon])=><Link key={to} to={to} className={cn('flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-semibold',path===to||path.startsWith(`${to}/`)?'bg-brand text-white':'hover:bg-mist')}><Icon size={18}/>{label}</Link>)}</nav><div className="mt-8 rounded-xl bg-mist p-3 text-xs text-slate-500"><b className="block text-ink">SINAESTA CBT</b>Khusus ujian, kuis, dan tryout</div></aside><div className="lg:pl-64"><header className="flex h-16 items-center justify-between border-b bg-white px-4 sm:px-6"><button className="lg:hidden" aria-label="Buka menu" onClick={()=>setOpen(true)}><Menu/></button><p className="hidden text-sm text-slate-500 sm:block">{admin?'Administrasi sistem ujian':'Portal peserta ujian'}</p><button className="flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold" aria-label="Menu akun"><span className="grid h-8 w-8 place-items-center rounded-full bg-brand text-xs text-white">AS</span><span className="hidden sm:inline">Aditya Saputra</span><ChevronDown size={14}/></button></header><main className="container-app py-6 lg:py-8"><Outlet/></main></div>{open&&<button aria-label="Tutup navigasi" className="fixed inset-0 z-30 bg-black/30 lg:hidden" onClick={()=>setOpen(false)}/>}</div>}
