import { AlertCircle, CheckCircle2, LoaderCircle, X } from 'lucide-react'
import { createContext, useContext, useState, type ReactNode } from 'react'
import { cn } from '@/lib/utils'

export function PageState({kind,title,description,onRetry}:{kind:'loading'|'empty'|'error';title?:string;description?:string;onRetry?:()=>void}){
 if(kind==='loading') return <div role="status" aria-label="Memuat" className="space-y-3"><div className="skeleton h-8 w-48"/><div className="grid gap-4 md:grid-cols-3">{[1,2,3].map(i=><div key={i} className="skeleton h-32"/>)}</div></div>
 return <div className="card py-12 text-center"><AlertCircle className="mx-auto mb-3 text-slate-400"/><h2 className="font-bold">{title ?? (kind==='empty'?'Belum ada data':'Terjadi kendala')}</h2><p className="mt-1 text-sm text-slate-500">{description ?? 'Coba kembali beberapa saat lagi.'}</p>{kind==='error'&&<button className="btn-secondary mt-4" onClick={onRetry}>Coba lagi</button>}</div>
}
type Toast={id:number;message:string}; const ToastContext=createContext<(message:string)=>void>(()=>{})
export const useToast=()=>useContext(ToastContext)
export function ToastProvider({children}:{children:ReactNode}){const [items,setItems]=useState<Toast[]>([]); const show=(message:string)=>{const id=Date.now();setItems(x=>[...x,{id,message}]);setTimeout(()=>setItems(x=>x.filter(t=>t.id!==id)),3500)};return <ToastContext.Provider value={show}>{children}<div className="fixed bottom-4 right-4 z-50 space-y-2" aria-live="polite">{items.map(t=><div key={t.id} className="flex items-center gap-2 rounded-xl bg-ink px-4 py-3 text-sm text-white shadow-soft"><CheckCircle2 size={18}/>{t.message}<button aria-label="Tutup" onClick={()=>setItems(x=>x.filter(v=>v.id!==t.id))}><X size={16}/></button></div>)}</div></ToastContext.Provider>}
export function ConfirmDialog({open,title,description,onCancel,onConfirm,busy}:{open:boolean;title:string;description:string;onCancel:()=>void;onConfirm:()=>void;busy?:boolean}){if(!open)return null;return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onCancel()}><div role="alertdialog" aria-modal="true" aria-labelledby="confirm-title" className="card max-w-md"><h2 id="confirm-title" className="text-lg font-bold">{title}</h2><p className="mt-2 text-sm text-slate-600">{description}</p><div className="mt-6 flex justify-end gap-2"><button className="btn-secondary" onClick={onCancel}>Batal</button><button className="btn-primary" onClick={onConfirm} disabled={busy}>{busy&&<LoaderCircle className="animate-spin" size={16}/>}Konfirmasi</button></div></div></div>}
export function Stat({label,value,detail,className}:{label:string;value:string;detail?:string;className?:string}){return <div className={cn('card',className)}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-extrabold">{value}</p>{detail&&<p className="mt-1 text-xs text-slate-500">{detail}</p>}</div>}
