<?php
declare(strict_types=1);
namespace Sinaesta\Identity\Infrastructure;
use PDO;
final readonly class AuthRepository
{
    public function __construct(private PDO $pdo) {}
    public function pdo(): PDO { return $this->pdo; }
    public function findUserByEmail(string $email): ?array { $s=$this->pdo->prepare('SELECT id, public_id, email, password_hash, status, email_verified_at, name FROM users WHERE email=:email LIMIT 1'); $s->execute(['email'=>$email]); $r=$s->fetch(); return $r ?: null; }
    public function findUserByPublicId(string $id): ?array { $s=$this->pdo->prepare('SELECT id, public_id, email, password_hash, status, email_verified_at, name FROM users WHERE public_id=:id LIMIT 1'); $s->execute(['id'=>$id]); $r=$s->fetch(); return $r ?: null; }
    public function createUser(string $publicId,string $name,string $email,string $hash): int { $s=$this->pdo->prepare("INSERT INTO users (public_id,name,email,password_hash,status,created_at,updated_at) VALUES (:id,:name,:email,:hash,'active',NOW(),NOW())"); $s->execute(['id'=>$publicId,'name'=>$name,'email'=>$email,'hash'=>$hash]); return (int)$this->pdo->lastInsertId(); }
    public function createProfile(int $userId,string $name): void { $s=$this->pdo->prepare('INSERT INTO profiles (public_id,user_id,display_name,created_at,updated_at) VALUES (:id,:user,:name,NOW(),NOW())'); $s->execute(['id'=>bin2hex(random_bytes(16)),'user'=>$userId,'name'=>$name]); }
    public function createSession(int $userId,string $publicId,string $hash,string $expires,string $agent,?string $ipHash): void { $s=$this->pdo->prepare('INSERT INTO user_sessions (public_id,user_id,token_hash,expires_at,user_agent,ip_hash,created_at,last_used_at) VALUES (:id,:user,:hash,:expires,:agent,:ip,NOW(),NOW())'); $s->execute(['id'=>$publicId,'user'=>$userId,'hash'=>$hash,'expires'=>$expires,'agent'=>mb_substr($agent,0,512),'ip'=>$ipHash]); }
    public function findActiveSession(string $hash): ?array { $sql="SELECT u.id internal_id,u.public_id,u.name,u.email,u.status,u.email_verified_at,s.public_id session_id,s.expires_at FROM user_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=:hash AND s.revoked_at IS NULL AND s.expires_at>UTC_TIMESTAMP() LIMIT 1"; $s=$this->pdo->prepare($sql); $s->execute(['hash'=>$hash]); $r=$s->fetch(); if(!$r)return null; $r['roles']=$this->roles((int)$r['internal_id']); $r['permissions']=$this->permissions((int)$r['internal_id']); return $r; }
    private function roles(int $id): array { $s=$this->pdo->prepare('SELECT r.slug FROM roles r JOIN user_roles ur ON ur.role_id=r.id WHERE ur.user_id=:id'); $s->execute(['id'=>$id]); return $s->fetchAll(PDO::FETCH_COLUMN); }
    private function permissions(int $id): array { $s=$this->pdo->prepare('SELECT DISTINCT p.slug FROM permissions p JOIN role_permissions rp ON rp.permission_id=p.id JOIN user_roles ur ON ur.role_id=rp.role_id WHERE ur.user_id=:id'); $s->execute(['id'=>$id]); return $s->fetchAll(PDO::FETCH_COLUMN); }
    public function revokeSession(int $userId,string $sessionId): bool { $s=$this->pdo->prepare('UPDATE user_sessions SET revoked_at=NOW() WHERE user_id=:user AND public_id=:session AND revoked_at IS NULL'); $s->execute(['user'=>$userId,'session'=>$sessionId]); return $s->rowCount()>0; }
    public function revokeAllSessions(int $userId): void { $s=$this->pdo->prepare('UPDATE user_sessions SET revoked_at=NOW() WHERE user_id=:user AND revoked_at IS NULL'); $s->execute(['user'=>$userId]); }
    public function sessions(int $userId): array { $s=$this->pdo->prepare('SELECT public_id id,user_agent,created_at,last_used_at,expires_at FROM user_sessions WHERE user_id=:user AND revoked_at IS NULL AND expires_at>NOW() ORDER BY created_at DESC LIMIT 100'); $s->execute(['user'=>$userId]); return $s->fetchAll(); }
    public function loginHistory(?int $userId,string $email,string $outcome,string $agent,?string $ipHash): void { $s=$this->pdo->prepare('INSERT INTO login_histories (public_id,user_id,email_hash,outcome,user_agent,ip_hash,created_at) VALUES (:id,:user,:email,:outcome,:agent,:ip,NOW())'); $s->execute(['id'=>bin2hex(random_bytes(16)),'user'=>$userId,'email'=>hash('sha256',$email),'outcome'=>$outcome,'agent'=>mb_substr($agent,0,512),'ip'=>$ipHash]); }
    public function storeOneTimeToken(string $table,int $userId,string $hash,string $expires): void { if(!in_array($table,['password_reset_tokens','email_verification_tokens'],true)) throw new \InvalidArgumentException('Invalid token table'); $s=$this->pdo->prepare("INSERT INTO {$table} (public_id,user_id,token_hash,expires_at,created_at) VALUES (:id,:user,:hash,:expires,NOW())"); $s->execute(['id'=>bin2hex(random_bytes(16)),'user'=>$userId,'hash'=>$hash,'expires'=>$expires]); }
    public function consumeToken(string $table,string $hash): ?int { if(!in_array($table,['password_reset_tokens','email_verification_tokens'],true)) throw new \InvalidArgumentException('Invalid token table'); $this->pdo->beginTransaction(); try { $s=$this->pdo->prepare("SELECT id,user_id FROM {$table} WHERE token_hash=:hash AND used_at IS NULL AND expires_at>NOW() FOR UPDATE"); $s->execute(['hash'=>$hash]); $r=$s->fetch(); if(!$r){$this->pdo->rollBack();return null;} $u=$this->pdo->prepare("UPDATE {$table} SET used_at=NOW() WHERE id=:id");$u->execute(['id'=>$r['id']]);$this->pdo->commit();return (int)$r['user_id']; } catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;} }
    public function updatePassword(int $id,string $hash): void { $s=$this->pdo->prepare('UPDATE users SET password_hash=:hash,password_changed_at=NOW(),updated_at=NOW() WHERE id=:id');$s->execute(compact('id','hash')); }
    public function verifyEmail(int $id): void { $s=$this->pdo->prepare('UPDATE users SET email_verified_at=COALESCE(email_verified_at,NOW()),updated_at=NOW() WHERE id=:id');$s->execute(['id'=>$id]); }
}
