<?php
declare(strict_types=1);
require dirname(__DIR__) . '/vendor/autoload.php';
use Sinaesta\Shared\Http\Request; use Sinaesta\Shared\Http\Response; use Sinaesta\Shared\Http\Router;
use Sinaesta\QuestionBank\Application\QuestionValidator; use Sinaesta\QuestionBank\Http\ParticipantQuestionResource;
use Sinaesta\Assessment\Application\ScoringService;
use Sinaesta\Billing\Infrastructure\LocalPaymentGateway;
use Sinaesta\Learning\Application\RecommendationScorer;
$failures=[];
$assert=static function(bool $condition,string $message) use (&$failures): void { if(!$condition)$failures[]=$message; };
$router=new Router();
$router->group('/api/v1',static function(Router $router): void { $router->get('/items/{id}',static fn(Request $r): Response=>Response::success('ok',['id'=>$r->attribute('id')]));$router->post('/items',static fn(Request $r): Response=>Response::success('created',null,201)); });
$found=$router->dispatch(new Request('GET','/api/v1/items/abc%20123'));
$assert($found->status===200 && $found->payload['data']['id']==='abc 123','router matches and decodes route parameters');
$assert($router->dispatch(new Request('DELETE','/api/v1/items/1'))->status===405,'router returns 405 for matched path with invalid method');
$assert($router->dispatch(new Request('GET','/missing'))->status===404,'router returns 404 for unknown path');
$error=Response::error('Validasi gagal',422,['email'=>['Email wajib diisi.']]);
$assert($error->payload['success']===false && $error->payload['errors']['email'][0]==='Email wajib diisi.','error response follows envelope');
$validator=new QuestionValidator();
$valid=['stem'=>'Stem','learning_objective'=>'Objective','category_id'=>'category','topic_id'=>'topic','difficulty'=>'medium','options'=>[['content'=>'A','is_correct'=>true],['content'=>'B','is_correct'=>false]]];
$assert($validator->validate($valid)===[],'valid single best answer passes validation');
$invalid=$valid;$invalid['options']=[['content'=>' Same ','is_correct'=>true],['content'=>'same','is_correct'=>true]];
$invalidErrors=$validator->validate($invalid);
$assert(isset($invalidErrors['options'])&&count($invalidErrors['options'])===2,'duplicate options and multiple correct answers are rejected');
$approvalErrors=$validator->validate($valid,true,true);
$assert(isset($approvalErrors['main_explanation'],$approvalErrors['references']),'approval and publish requirements are enforced');
$participant=ParticipantQuestionResource::from(['id'=>'q','question_type'=>'single_best_answer','stem'=>'S','clinical_vignette'=>null,'difficulty'=>'easy','main_explanation'=>'secret','options'=>[['id'=>'o','content'=>'A','is_correct'=>true,'explanation'=>'secret']],'media'=>[]]);
$encoded=json_encode($participant,JSON_THROW_ON_ERROR);
$assert(!str_contains($encoded,'is_correct')&&!str_contains($encoded,'explanation'),'participant resource omits answer key and explanations');
$score=(new ScoringService())->calculate([['selected_option_id'=>'a','correct_option_id'=>'a','topic'=>'T','category'=>'C','difficulty'=>'easy'],['selected_option_id'=>'b','correct_option_id'=>'c','topic'=>'T','category'=>'C','difficulty'=>'hard'],['selected_option_id'=>null,'correct_option_id'=>'d','topic'=>'U','category'=>'C','difficulty'=>'hard']],90);
$assert($score['correct']===1&&$score['incorrect']===1&&$score['unanswered']===1&&$score['percentage_score']===33.33,'server scoring counts all answer states');
$assert($score['average_time_seconds']===30.0&&count($score['analytics'])===5,'duration and dimension analytics are calculated');
$gateway=new LocalPaymentGateway('test-secret','https://pay.test');
$timestamp=(string)time();$body='{"event_id":"evt-1"}';$signature=hash_hmac('sha256',$timestamp.'.'.$body,'test-secret');
$assert($gateway->verifyWebhook(['x-payment-timestamp'=>$timestamp,'x-payment-signature'=>$signature],$body),'payment webhook accepts a valid HMAC and timestamp');
$assert(!$gateway->verifyWebhook(['x-payment-timestamp'=>$timestamp,'x-payment-signature'=>'invalid'],$body),'payment webhook rejects an invalid HMAC');
$recommendation=(new RecommendationScorer())->score(['attempts_count'=>4,'correct_count'=>1,'incorrect_count'=>3,'days_since_answered'=>45,'average_response_seconds'=>120]);
$assert($recommendation['score']===80.0&&count($recommendation['reasons'])===4,'recommendation scoring combines weakness, recency, recurrence, and time rules');
if($failures!==[]){foreach($failures as $failure)fwrite(STDERR,"FAIL: {$failure}\n");exit(1);} echo "13 tests passed\n";
