SET NAMES utf8mb4;

CREATE TABLE subscription_plans (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,slug VARCHAR(80) NOT NULL UNIQUE,name VARCHAR(160) NOT NULL,description TEXT NULL,plan_type ENUM('subscription','token','institution') NOT NULL,duration_days SMALLINT UNSIGNED NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,is_featured TINYINT(1) NOT NULL DEFAULT 0,sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE plan_prices (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,plan_id BIGINT UNSIGNED NOT NULL,amount BIGINT UNSIGNED NOT NULL,currency CHAR(3) NOT NULL DEFAULT 'IDR',billing_type ENUM('one_time','recurring','quote') NOT NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,valid_from DATETIME NOT NULL,valid_until DATETIME NULL,created_at DATETIME NOT NULL,INDEX plan_prices_active_idx(plan_id,is_active,valid_from,valid_until),FOREIGN KEY(plan_id) REFERENCES subscription_plans(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE plan_features (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,entitlement_key VARCHAR(80) NOT NULL UNIQUE,name VARCHAR(160) NOT NULL,description VARCHAR(500) NULL,sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE plan_feature_values (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,plan_id BIGINT UNSIGNED NOT NULL,feature_id BIGINT UNSIGNED NOT NULL,value_type ENUM('integer','boolean','string') NOT NULL,integer_value BIGINT NULL,boolean_value TINYINT(1) NULL,string_value VARCHAR(255) NULL,created_at DATETIME NOT NULL,UNIQUE(plan_id,feature_id),FOREIGN KEY(plan_id) REFERENCES subscription_plans(id),FOREIGN KEY(feature_id) REFERENCES plan_features(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE transactions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,user_id BIGINT UNSIGNED NOT NULL,status ENUM('pending','paid','failed','expired','cancelled','refunded') NOT NULL,subtotal BIGINT UNSIGNED NOT NULL,discount_amount BIGINT UNSIGNED NOT NULL,total BIGINT UNSIGNED NOT NULL,currency CHAR(3) NOT NULL,gateway VARCHAR(40) NOT NULL,gateway_reference VARCHAR(160) NULL UNIQUE,expires_at DATETIME NOT NULL,paid_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX transactions_user_idx(user_id,created_at),INDEX transactions_expiry_idx(status,expires_at),FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE transaction_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,transaction_id BIGINT UNSIGNED NOT NULL,plan_id BIGINT UNSIGNED NOT NULL,price_id BIGINT UNSIGNED NOT NULL,description VARCHAR(255) NOT NULL,quantity INT UNSIGNED NOT NULL,unit_amount BIGINT UNSIGNED NOT NULL,total_amount BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL,FOREIGN KEY(transaction_id) REFERENCES transactions(id),FOREIGN KEY(plan_id) REFERENCES subscription_plans(id),FOREIGN KEY(price_id) REFERENCES plan_prices(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE subscriptions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,user_id BIGINT UNSIGNED NOT NULL,plan_id BIGINT UNSIGNED NOT NULL,source_transaction_id BIGINT UNSIGNED NULL UNIQUE,status ENUM('active','expired','cancelled') NOT NULL,starts_at DATETIME NOT NULL,expires_at DATETIME NULL,auto_renew TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX subscription_active_idx(user_id,status,expires_at),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(plan_id) REFERENCES subscription_plans(id),FOREIGN KEY(source_transaction_id) REFERENCES transactions(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE subscription_histories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,subscription_id BIGINT UNSIGNED NOT NULL,event_type VARCHAR(40) NOT NULL,from_status VARCHAR(20) NULL,to_status VARCHAR(20) NOT NULL,metadata JSON NULL,created_at DATETIME NOT NULL,FOREIGN KEY(subscription_id) REFERENCES subscriptions(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE user_entitlements (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,user_id BIGINT UNSIGNED NOT NULL,subscription_id BIGINT UNSIGNED NULL,entitlement_key VARCHAR(80) NOT NULL,value_type ENUM('integer','boolean','string') NOT NULL,integer_value BIGINT NULL,boolean_value TINYINT(1) NULL,string_value VARCHAR(255) NULL,starts_at DATETIME NOT NULL,expires_at DATETIME NULL,revoked_at DATETIME NULL,created_at DATETIME NOT NULL,INDEX entitlement_active_idx(user_id,entitlement_key,revoked_at,expires_at),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(subscription_id) REFERENCES subscriptions(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE entitlement_usage (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,entitlement_key VARCHAR(80) NOT NULL,period_start DATETIME NOT NULL,period_end DATETIME NOT NULL,used_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,updated_at DATETIME NOT NULL,UNIQUE(user_id,entitlement_key,period_start),FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE tryout_token_wallets (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,user_id BIGINT UNSIGNED NOT NULL UNIQUE,balance INT UNSIGNED NOT NULL DEFAULT 0,expires_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE tryout_token_transactions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,wallet_id BIGINT UNSIGNED NOT NULL,transaction_id BIGINT UNSIGNED NULL,type ENUM('credit','debit','expire','refund') NOT NULL,amount INT NOT NULL,description VARCHAR(255) NOT NULL,created_at DATETIME NOT NULL,UNIQUE(transaction_id,type),FOREIGN KEY(wallet_id) REFERENCES tryout_token_wallets(id),FOREIGN KEY(transaction_id) REFERENCES transactions(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE payment_webhooks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,gateway VARCHAR(40) NOT NULL,event_id VARCHAR(160) NOT NULL,payload_hash CHAR(64) NOT NULL,processing_status ENUM('processed','rejected','failed') NOT NULL,received_at DATETIME NOT NULL,processed_at DATETIME NULL,UNIQUE(gateway,event_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE payment_status_histories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,transaction_id BIGINT UNSIGNED NOT NULL,from_status VARCHAR(20) NULL,to_status VARCHAR(20) NOT NULL,source VARCHAR(40) NOT NULL,created_at DATETIME NOT NULL,FOREIGN KEY(transaction_id) REFERENCES transactions(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE vouchers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,code_hash CHAR(64) NOT NULL UNIQUE,name VARCHAR(160) NOT NULL,discount_type ENUM('fixed','percentage') NOT NULL,discount_value BIGINT UNSIGNED NOT NULL,max_discount_amount BIGINT UNSIGNED NULL,usage_limit INT UNSIGNED NULL,used_count INT UNSIGNED NOT NULL DEFAULT 0,per_user_limit INT UNSIGNED NULL,status ENUM('active','expired','disabled') NOT NULL,starts_at DATETIME NOT NULL,expires_at DATETIME NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX vouchers_expiry_idx(status,expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE voucher_rules (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,voucher_id BIGINT UNSIGNED NOT NULL,plan_id BIGINT UNSIGNED NULL,minimum_subtotal BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL,FOREIGN KEY(voucher_id) REFERENCES vouchers(id),FOREIGN KEY(plan_id) REFERENCES subscription_plans(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE voucher_usages (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,voucher_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,transaction_id BIGINT UNSIGNED NOT NULL UNIQUE,discount_amount BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL,INDEX voucher_user_idx(voucher_id,user_id),FOREIGN KEY(voucher_id) REFERENCES vouchers(id),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(transaction_id) REFERENCES transactions(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE invoices (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,transaction_id BIGINT UNSIGNED NOT NULL UNIQUE,gateway_invoice_id VARCHAR(160) NOT NULL UNIQUE,status ENUM('pending','paid','expired','cancelled') NOT NULL,payment_url VARCHAR(1000) NOT NULL,amount BIGINT UNSIGNED NOT NULL,currency CHAR(3) NOT NULL,expires_at DATETIME NOT NULL,paid_at DATETIME NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,FOREIGN KEY(transaction_id) REFERENCES transactions(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE refunds (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,public_id CHAR(32) NOT NULL UNIQUE,transaction_id BIGINT UNSIGNED NOT NULL,gateway_reference VARCHAR(160) NULL,status ENUM('pending','succeeded','failed') NOT NULL,amount BIGINT UNSIGNED NOT NULL,reason VARCHAR(500) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,FOREIGN KEY(transaction_id) REFERENCES transactions(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO subscription_plans(public_id,slug,name,description,plan_type,duration_days,is_active,is_featured,sort_order,created_at,updated_at) VALUES
('10000000000000000000000000000001','gratis','Paket Gratis','Akses belajar dasar tanpa batas waktu','subscription',NULL,1,0,10,UTC_TIMESTAMP(),UTC_TIMESTAMP()),
('10000000000000000000000000000002','basic-30','Paket Basic 30 Hari','Latihan terarah selama 30 hari','subscription',30,1,0,20,UTC_TIMESTAMP(),UTC_TIMESTAMP()),
('10000000000000000000000000000003','intensif-30','Paket Intensif 30 Hari','Persiapan intensif selama 30 hari','subscription',30,1,1,30,UTC_TIMESTAMP(),UTC_TIMESTAMP()),
('10000000000000000000000000000004','pro-90','Paket Pro 90 Hari','Persiapan lengkap selama 90 hari','subscription',90,1,0,40,UTC_TIMESTAMP(),UTC_TIMESTAMP()),
('10000000000000000000000000000005','token-full-1','Token Full Tryout 1 Kali','Satu token full tryout','token',14,1,0,50,UTC_TIMESTAMP(),UTC_TIMESTAMP()),
('10000000000000000000000000000006','token-full-5','Paket Full Tryout 5 Kali','Lima token full tryout','token',30,1,0,60,UTC_TIMESTAMP(),UTC_TIMESTAMP()),
('10000000000000000000000000000007','token-full-10','Paket Full Tryout 10 Kali','Sepuluh token full tryout','token',60,1,0,70,UTC_TIMESTAMP(),UTC_TIMESTAMP()),
('10000000000000000000000000000008','institusi','Paket Institusi','Konfigurasi berdasarkan penawaran','institution',NULL,1,0,80,UTC_TIMESTAMP(),UTC_TIMESTAMP());
INSERT INTO plan_prices(public_id,plan_id,amount,currency,billing_type,is_active,valid_from,created_at) SELECT CONCAT('2',LPAD(id,31,'0')),id,CASE slug WHEN 'gratis' THEN 0 WHEN 'basic-30' THEN 49000 WHEN 'intensif-30' THEN 99000 WHEN 'pro-90' THEN 249000 WHEN 'token-full-1' THEN 15000 WHEN 'token-full-5' THEN 59000 WHEN 'token-full-10' THEN 99000 ELSE 0 END,'IDR',IF(slug='institusi','quote','one_time'),1,'2026-01-01 00:00:00',UTC_TIMESTAMP() FROM subscription_plans;
INSERT INTO plan_features(public_id,entitlement_key,name,sort_order,created_at) VALUES
('30000000000000000000000000000001','daily_question_limit','Batas soal harian',10,UTC_TIMESTAMP()),('30000000000000000000000000000002','monthly_question_limit','Batas soal bulanan',20,UTC_TIMESTAMP()),('30000000000000000000000000000003','total_question_limit','Batas total soal',30,UTC_TIMESTAMP()),('30000000000000000000000000000004','mini_tryout_limit','Batas mini tryout',40,UTC_TIMESTAMP()),('30000000000000000000000000000005','full_tryout_limit','Batas full tryout',50,UTC_TIMESTAMP()),('30000000000000000000000000000006','bookmark_limit','Batas bookmark',60,UTC_TIMESTAMP()),('30000000000000000000000000000007','history_retention_days','Retensi riwayat',70,UTC_TIMESTAMP()),('30000000000000000000000000000008','explanation_access','Akses pembahasan',80,UTC_TIMESTAMP()),('30000000000000000000000000000009','advanced_topic_analytics','Analitik topik',90,UTC_TIMESTAMP()),('30000000000000000000000000000010','difficulty_analytics','Analitik difficulty',100,UTC_TIMESTAMP()),('30000000000000000000000000000011','time_analytics','Analitik waktu',110,UTC_TIMESTAMP()),('30000000000000000000000000000012','wrong_answer_practice','Latihan soal salah',120,UTC_TIMESTAMP()),('30000000000000000000000000000013','adaptive_recommendation','Rekomendasi adaptif',130,UTC_TIMESTAMP()),('30000000000000000000000000000014','ad_free','Tanpa banner promosi',140,UTC_TIMESTAMP()),('30000000000000000000000000000015','tryout_token_balance','Saldo token tryout',150,UTC_TIMESTAMP());
INSERT INTO plan_feature_values(plan_id,feature_id,value_type,integer_value,boolean_value,string_value,created_at)
SELECT p.id,f.id,IF(f.entitlement_key IN ('explanation_access'),'string',IF(f.entitlement_key IN ('advanced_topic_analytics','difficulty_analytics','time_analytics','wrong_answer_practice','adaptive_recommendation','ad_free'),'boolean','integer')),
CASE f.entitlement_key WHEN 'daily_question_limit' THEN IF(p.slug='gratis',15,NULL) WHEN 'monthly_question_limit' THEN IF(p.slug='gratis',100,NULL) WHEN 'total_question_limit' THEN CASE p.slug WHEN 'basic-30' THEN 2000 WHEN 'intensif-30' THEN 10000 WHEN 'pro-90' THEN 30000 END WHEN 'mini_tryout_limit' THEN CASE p.slug WHEN 'gratis' THEN 1 WHEN 'basic-30' THEN 5 WHEN 'intensif-30' THEN 20 WHEN 'pro-90' THEN 60 END WHEN 'full_tryout_limit' THEN CASE p.slug WHEN 'basic-30' THEN 1 WHEN 'intensif-30' THEN 5 WHEN 'pro-90' THEN 15 END WHEN 'bookmark_limit' THEN CASE p.slug WHEN 'gratis' THEN 20 WHEN 'basic-30' THEN 500 ELSE -1 END WHEN 'history_retention_days' THEN CASE p.slug WHEN 'gratis' THEN 30 WHEN 'basic-30' THEN 30 WHEN 'intensif-30' THEN 30 WHEN 'pro-90' THEN 90 END WHEN 'tryout_token_balance' THEN CASE p.slug WHEN 'token-full-1' THEN 1 WHEN 'token-full-5' THEN 5 WHEN 'token-full-10' THEN 10 END END,
CASE WHEN f.entitlement_key='ad_free' THEN p.slug IN ('intensif-30','pro-90') WHEN f.entitlement_key='adaptive_recommendation' THEN p.slug='pro-90' WHEN f.entitlement_key IN ('advanced_topic_analytics','difficulty_analytics','time_analytics') THEN p.slug IN ('intensif-30','pro-90') WHEN f.entitlement_key='wrong_answer_practice' THEN p.slug IN ('basic-30','intensif-30','pro-90') END,
CASE WHEN f.entitlement_key='explanation_access' THEN IF(p.slug='gratis','limited','full') END,UTC_TIMESTAMP()
FROM subscription_plans p CROSS JOIN plan_features f WHERE p.slug<>'institusi' AND ((p.plan_type='token' AND f.entitlement_key IN ('tryout_token_balance','explanation_access')) OR (p.plan_type='subscription' AND f.entitlement_key<>'tryout_token_balance'));
