<?php
declare(strict_types=1);
namespace Sinaesta\Assessment\Application;

use Sinaesta\Assessment\Infrastructure\AssessmentRepository;
use Sinaesta\Shared\Http\HttpException;

final readonly class AssessmentService
{
    public function __construct(private AssessmentRepository $repository,private ScoringService $scoring){}
    public function config():array{return['modes'=>['topic','category','difficulty','random','daily','wrong','bookmark','mini_tryout','full_tryout','cbt'],'difficulties'=>['easy','medium','hard'],'scoring'=>['correct'=>1,'incorrect'=>0,'unanswered'=>0]];}
    public function tryouts():array{return$this->repository->tryouts();}
    public function tryout(string$id):array{return$this->repository->tryout($id)??throw new HttpException(404,'Tryout tidak ditemukan.');}
    public function startPractice(int$user,array$input):array{$code=(string)($input['template_id']??$input['mode']??'');$template=$this->repository->template($code)??throw new HttpException(404,'Template latihan tidak ditemukan.');return$this->start($user,$template,$input,null);}
    public function startTryout(int$user,string$id):array{$tryout=$this->repository->tryout($id,true)??throw new HttpException(404,'Tryout tidak ditemukan.');$now=time();if(!(bool)$tryout['active']||strtotime($tryout['starts_at'])>$now||strtotime($tryout['ends_at'])<=$now)throw new HttpException(409,'Tryout sedang tidak tersedia.');$template=$this->repository->template($tryout['template_public_id'])??throw new HttpException(409,'Template tryout tidak aktif.');return$this->start($user,$template,[],(int)$tryout['id']);}
    private function start(int$user,array$template,array$input,?int$tryout):array{$rules=$this->repository->rules((int)$template['id']);$roles=array_values(array_filter((array)($rules['allowed_roles']??[]),'is_string'));if(!$this->repository->hasRole($user,$roles))throw new HttpException(403,'Paket pengguna tidak berhak mengakses quiz ini.');$limit=(int)($rules['max_attempts']??0);if($limit>0&&$this->repository->attemptCount($user,(int)$template['id'],$tryout)>=$limit)throw new HttpException(429,'Batas attempt paket telah tercapai.');$token=(int)($rules['token_cost']??0);$seed=bin2hex(random_bytes(32));$input['_user']=$user;try{return$this->repository->transaction(function()use($user,$template,$input,$tryout,$seed,$token){$questions=$this->repository->questions($template,$input,$tryout,$seed);if(count($questions)!==(int)$template['question_count'])throw new HttpException(409,'Jumlah soal yang memenuhi aturan tidak mencukupi.');$attempt=$this->repository->createAttempt($user,$template,$tryout,$seed,$token);$this->repository->snapshot($attempt['internal_id'],$questions,$seed);$this->repository->debit($user,$token);$this->repository->event($attempt['internal_id'],$user,'attempt_started',['random_seed'=>$seed]);return$this->view($attempt['id'],$user);});}catch(\DomainException$e){throw new HttpException(409,$e->getMessage());}}
    public function view(string$id,int$user):array{$a=$this->owned($id,$user);return['id'=>$a['public_id'],'status'=>$a['status'],'mode'=>$a['mode'],'server_time'=>gmdate(DATE_ATOM),'started_at'=>$this->iso($a['started_at']),'expires_at'=>$this->iso($a['expires_at']),'questions'=>$this->repository->participantQuestions((int)$a['id'])];}
    public function save(string$id,string$question,int$user,array$input):array{$a=$this->active($id,$user);foreach(['option_id','client_answer_id','client_timestamp']as$key)if(!isset($input[$key])||!is_string($input[$key])||$input[$key]==='')throw new HttpException(422,'Payload autosave tidak lengkap.',[$key=>['Field wajib diisi.']]);if(!$this->uuid($input['client_answer_id']))throw new HttpException(422,'client_answer_id harus UUID.');$timestamp=date_create_immutable($input['client_timestamp']);if(!$timestamp)throw new HttpException(422,'client_timestamp harus ISO-8601.');try{$status=$this->repository->answer((int)$a['id'],$question,$input['option_id'],$input['client_answer_id'],$timestamp->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s'));$this->repository->event((int)$a['id'],$user,'answer_saved',['question_id'=>$question,'save_status'=>$status]);return['save_status'=>$status,'saved_at'=>gmdate(DATE_ATOM),'server_time'=>gmdate(DATE_ATOM),'expires_at'=>$this->iso($a['expires_at'])];}catch(\DomainException$e){throw new HttpException(422,$e->getMessage());}}
    public function flag(string$id,string$question,int$user,bool$set):void{$a=$this->active($id,$user);try{$this->repository->flag((int)$a['id'],$question,$set);$this->repository->event((int)$a['id'],$user,$set?'question_flagged':'question_unflagged',['question_id'=>$question]);}catch(\DomainException$e){throw new HttpException(422,$e->getMessage());}}
    public function submit(string$id,int$user,bool$automatic=false):array{return$this->repository->transaction(function()use($id,$user,$automatic){$a=$this->repository->attempt($id,$user,true)??throw new HttpException(404,'Attempt tidak ditemukan.');if(in_array($a['status'],['submitted','expired','auto_submitted'],true)){return$this->repository->result((int)$a['id'])??throw new HttpException(409,'Result attempt belum tersedia.');}if($a['status']!=='active')throw new HttpException(409,'Attempt tidak dapat disubmit.');$expired=strtotime($a['expires_at'])<=time();if(!$automatic&&$expired)throw new HttpException(409,'Waktu attempt telah habis; menunggu auto-submit.');$rows=$this->repository->scoreRows((int)$a['id']);if(count($rows)!==(int)$a['question_count'])throw new HttpException(409,'Integritas snapshot attempt tidak valid.');$duration=min((int)$a['duration_seconds'],max(0,time()-strtotime($a['started_at'])));$result=$this->scoring->calculate($rows,$duration);$status=$automatic?'auto_submitted':'submitted';$this->repository->persistResult($a,$result,$status);$this->repository->event((int)$a['id'],$user,$status,['score'=>$result['raw_score']]);return$result;});}
    public function result(string$id,int$user):array{$a=$this->owned($id,$user);return$this->repository->result((int)$a['id'])??throw new HttpException(409,'Attempt belum selesai.');}
    public function review(string$id,int$user):array{$a=$this->owned($id,$user);$afterAnswer=$a['explanation_policy']==='after_answer';if(!$afterAnswer&&$this->repository->result((int)$a['id'])===null)throw new HttpException(409,'Attempt belum selesai.');if(!$this->canReview($a,$user))throw new HttpException(403,'Pembahasan belum atau tidak tersedia.');return['attempt_id'=>$id,'questions'=>$this->repository->review((int)$a['id'],$afterAnswer),'available'=>true];}
    public function attempts(int$user):array{return$this->repository->myAttempts($user);} public function analytics(int$user):array{return$this->repository->aggregate($user);} public function wrong(int$user):array{return$this->repository->questionList($user,'wrong');}public function bookmarks(int$user):array{return$this->repository->questionList($user,'bookmark');}
    private function owned(string$id,int$user):array{return$this->repository->attempt($id,$user)??throw new HttpException(404,'Attempt tidak ditemukan.');}
    private function active(string$id,int$user):array{$a=$this->owned($id,$user);if($a['status']!=='active')throw new HttpException(409,'Attempt tidak aktif.');if(strtotime($a['expires_at'])<=time())throw new HttpException(409,'Waktu attempt telah habis.');return$a;}
    private function canReview(array$a,int$user):bool{return match($a['explanation_policy']){'unavailable'=>false,'after_tryout_period'=>$a['tryout_ends_at']!==null&&strtotime($a['tryout_ends_at'])<=time(),default=>true};}
    private function iso(?string$value):?string{return$value===null?null:gmdate(DATE_ATOM,strtotime($value));} private function uuid(string$value):bool{return(bool)preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i',$value);}
}
