<?php
declare(strict_types=1);
namespace Sinaesta\Assessment\Infrastructure;

use PDO;
use Sinaesta\QuestionBank\Infrastructure\QuestionRepository;

final readonly class AssessmentRepository
{
    public function __construct(private PDO $pdo){}
    public function transaction(callable $work): mixed {$this->pdo->beginTransaction();try{$value=$work();$this->pdo->commit();return$value;}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
    public function template(string $idOrCode): ?array {$s=$this->pdo->prepare('SELECT * FROM quiz_templates WHERE (public_id=:id OR code=:id) AND active=1 LIMIT 1');$s->execute(['id'=>$idOrCode]);$r=$s->fetch();return$r?:null;}
    public function rules(int $template): array {$s=$this->pdo->prepare('SELECT rule_key,rule_value FROM quiz_template_rules WHERE template_id=:id');$s->execute(['id'=>$template]);$out=[];foreach($s->fetchAll() as$r)$out[$r['rule_key']]=json_decode($r['rule_value'],true);return$out;}
    public function tryout(string $id, bool $lock=false): ?array {$s=$this->pdo->prepare('SELECT t.*,q.public_id template_public_id,q.name template_name,q.duration_seconds,q.question_count,q.explanation_policy FROM tryouts t JOIN quiz_templates q ON q.id=t.template_id WHERE t.public_id=:id'.($lock?' FOR UPDATE':''));$s->execute(['id'=>$id]);$r=$s->fetch();return$r?:null;}
    public function tryouts(): array {return$this->pdo->query('SELECT t.public_id id,t.title,t.description,t.starts_at,t.ends_at,t.result_available_at,t.max_attempts,q.mode,q.question_count,q.duration_seconds FROM tryouts t JOIN quiz_templates q ON q.id=t.template_id WHERE t.active=1 ORDER BY t.starts_at DESC')->fetchAll();}
    public function attemptCount(int $user,int $template,?int $tryout=null): int {$sql='SELECT COUNT(*) FROM attempts WHERE user_id=:user AND template_id=:template AND status NOT IN ("cancelled","invalidated")'.($tryout===null?'':' AND tryout_id=:tryout');$s=$this->pdo->prepare($sql);$p=['user'=>$user,'template'=>$template];if($tryout!==null)$p['tryout']=$tryout;$s->execute($p);return(int)$s->fetchColumn();}
    public function hasRole(int$user,array$allowed):bool{if($allowed===[])return true;$marks=implode(',',array_fill(0,count($allowed),'?'));$s=$this->pdo->prepare("SELECT 1 FROM user_roles ur JOIN roles r ON r.id=ur.role_id WHERE ur.user_id=? AND r.slug IN ({$marks}) LIMIT 1");$s->execute([$user,...$allowed]);return(bool)$s->fetchColumn();}
    public function questions(array $template,array $input,?int $tryout,string $seed): array {if($tryout!==null){$s=$this->pdo->prepare("SELECT q.* FROM tryout_questions tq JOIN questions q ON q.id=tq.question_id WHERE tq.tryout_id=:id AND q.status='published' ORDER BY tq.question_order");$s->execute(['id'=>$tryout]);return$s->fetchAll();}$where=["q.status='published'"];$p=[];foreach(['topic_id'=>'topic','category_id'=>'category','difficulty'=>'difficulty']as$field=>$column)if(isset($input[$field])){$where[]=$column==='difficulty'?"q.difficulty=:{$field}":($column==='topic'?"t.public_id=:{$field}":"c.public_id=:{$field}");$p[$field]=$input[$field];}$mode=$template['mode'];if($mode==='wrong'){$where[]='EXISTS(SELECT 1 FROM user_question_histories h WHERE h.question_id=q.id AND h.user_id=:user AND h.incorrect_count>h.correct_count)';$p['user']=$input['_user'];}if($mode==='bookmark'){$where[]='EXISTS(SELECT 1 FROM user_bookmarks b WHERE b.question_id=q.id AND b.user_id=:user)';$p['user']=$input['_user'];}$sql='SELECT q.* FROM questions q JOIN question_topics t ON t.id=q.topic_id JOIN question_categories c ON c.id=q.category_id WHERE '.implode(' AND ',$where).' ORDER BY SHA2(CONCAT(q.id,:seed),256) LIMIT '.(int)$template['question_count'];$p['seed']=$seed;$s=$this->pdo->prepare($sql);$s->execute($p);return$s->fetchAll();}
    public function createAttempt(int$user,array$template,?int$tryout,string$seed,int$token): array {$id=QuestionRepository::uuid();$s=$this->pdo->prepare("INSERT INTO attempts(public_id,user_id,template_id,tryout_id,status,random_seed,question_count,duration_seconds,token_cost,started_at,expires_at,created_at,updated_at) VALUES(:id,:user,:template,:tryout,'active',:seed,:count,:duration,:token,UTC_TIMESTAMP(),DATE_ADD(UTC_TIMESTAMP(),INTERVAL :duration2 SECOND),UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute(['id'=>$id,'user'=>$user,'template'=>$template['id'],'tryout'=>$tryout,'seed'=>$seed,'count'=>$template['question_count'],'duration'=>$template['duration_seconds'],'token'=>$token,'duration2'=>$template['duration_seconds']]);return['internal_id'=>(int)$this->pdo->lastInsertId(),'id'=>$id];}
    public function snapshot(int$attempt,array$questions,string$seed): void {$q=$this->pdo->prepare('SELECT q.*,c.public_id category_public_id,c.name category_name,t.public_id topic_public_id,t.name topic_name FROM questions q JOIN question_categories c ON c.id=q.category_id JOIN question_topics t ON t.id=q.topic_id WHERE q.id=:id');$opts=$this->pdo->prepare('SELECT * FROM question_options WHERE question_id=:id ORDER BY SHA2(CONCAT(id,:seed),256)');$sq=$this->pdo->prepare('INSERT INTO attempt_question_snapshots(public_id,attempt_id,question_id,question_version,question_order,stem,clinical_vignette,explanation,learning_objective,category_id,category_name,topic_id,topic_name,difficulty,correct_option_public_id) VALUES(:uuid,:attempt,:question,:version,:position,:stem,:vignette,:explanation,:objective,:category_id,:category_name,:topic_id,:topic_name,:difficulty,:correct)');$so=$this->pdo->prepare('INSERT INTO attempt_option_snapshots(public_id,attempt_question_snapshot_id,source_option_public_id,option_order,content,explanation) VALUES(:uuid,:question,:source,:position,:content,:explanation)');foreach(array_values($questions)as$i=>$base){$q->execute(['id'=>$base['id']]);$row=$q->fetch();$opts->execute(['id'=>$row['id'],'seed'=>$seed]);$options=$opts->fetchAll();$correct=array_values(array_filter($options,fn($o)=>(bool)$o['is_correct']))[0]??null;if(!$correct)throw new \DomainException('Soal tidak memiliki jawaban benar.');$sq->execute(['uuid'=>QuestionRepository::uuid(),'attempt'=>$attempt,'question'=>$row['id'],'version'=>$row['current_version'],'position'=>$i+1,'stem'=>$row['stem'],'vignette'=>$row['clinical_vignette'],'explanation'=>$row['main_explanation'],'objective'=>$row['learning_objective'],'category_id'=>$row['category_public_id'],'category_name'=>$row['category_name'],'topic_id'=>$row['topic_public_id'],'topic_name'=>$row['topic_name'],'difficulty'=>$row['difficulty'],'correct'=>$correct['public_id']]);$snapshot=(int)$this->pdo->lastInsertId();foreach($options as$j=>$option)$so->execute(['uuid'=>QuestionRepository::uuid(),'question'=>$snapshot,'source'=>$option['public_id'],'position'=>$j+1,'content'=>$option['content'],'explanation'=>$option['explanation']]);}}
    public function debit(int$user,int$cost): void {if($cost===0)return;$s=$this->pdo->prepare('UPDATE users SET quiz_tokens=quiz_tokens-:cost WHERE id=:id AND quiz_tokens>=:cost');$s->execute(['cost'=>$cost,'id'=>$user]);if($s->rowCount()!==1)throw new \DomainException('Token quiz tidak mencukupi.');}
    public function attempt(string$id,int$user,bool$lock=false): ?array {$s=$this->pdo->prepare('SELECT a.*,q.mode,q.explanation_policy,t.ends_at tryout_ends_at,t.result_available_at FROM attempts a JOIN quiz_templates q ON q.id=a.template_id LEFT JOIN tryouts t ON t.id=a.tryout_id WHERE a.public_id=:id AND a.user_id=:user'.($lock?' FOR UPDATE':''));$s->execute(['id'=>$id,'user'=>$user]);$r=$s->fetch();return$r?:null;}
    public function participantQuestions(int$attempt): array {$s=$this->pdo->prepare('SELECT s.id internal_id,s.question_id,s.question_order,s.public_id id,s.stem,s.clinical_vignette,s.difficulty,s.category_id,s.category_name,s.topic_id,s.topic_name,o.public_id option_id,o.option_order,o.content,a.option_snapshot_id,IF(f.attempt_id IS NULL,0,1) flagged FROM attempt_question_snapshots s JOIN attempt_option_snapshots o ON o.attempt_question_snapshot_id=s.id LEFT JOIN attempt_answers a ON a.attempt_question_snapshot_id=s.id LEFT JOIN attempt_flags f ON f.attempt_question_snapshot_id=s.id AND f.attempt_id=s.attempt_id WHERE s.attempt_id=:id ORDER BY s.question_order,o.option_order');$s->execute(['id'=>$attempt]);$out=[];foreach($s->fetchAll()as$r){$key=$r['id'];$out[$key]??=['id'=>$key,'order'=>(int)$r['question_order'],'stem'=>$r['stem'],'clinical_vignette'=>$r['clinical_vignette'],'difficulty'=>$r['difficulty'],'category'=>['id'=>$r['category_id'],'name'=>$r['category_name']],'topic'=>['id'=>$r['topic_id'],'name'=>$r['topic_name']],'selected_option_id'=>null,'flagged'=>(bool)$r['flagged'],'options'=>[]];$out[$key]['options'][]=['id'=>$r['option_id'],'order'=>(int)$r['option_order'],'content'=>$r['content']];if($r['option_snapshot_id']!==null&&$r['option_snapshot_id']===$this->optionInternal($r['option_id']))$out[$key]['selected_option_id']=$r['option_id'];}return array_values($out);}
    private function optionInternal(string$id): string {$s=$this->pdo->prepare('SELECT id FROM attempt_option_snapshots WHERE public_id=:id');$s->execute(['id'=>$id]);return(string)$s->fetchColumn();}
    public function answer(int$attempt,string$question,string$option,string$client,?string$timestamp): string {$s=$this->pdo->prepare('SELECT qs.id question_id,os.id option_id FROM attempt_question_snapshots qs JOIN attempt_option_snapshots os ON os.attempt_question_snapshot_id=qs.id WHERE qs.attempt_id=:attempt AND qs.public_id=:question AND os.public_id=:option');$s->execute(['attempt'=>$attempt,'question'=>$question,'option'=>$option]);$row=$s->fetch();if(!$row)throw new \DomainException('Soal atau opsi tidak termasuk snapshot attempt.');$duplicate=$this->pdo->prepare('SELECT 1 FROM attempt_answers WHERE attempt_id=:attempt AND client_answer_id=:client');$duplicate->execute(['attempt'=>$attempt,'client'=>$client]);if($duplicate->fetchColumn())return'duplicate';$save=$this->pdo->prepare('INSERT INTO attempt_answers(attempt_id,attempt_question_snapshot_id,option_snapshot_id,client_answer_id,client_timestamp,answered_at) VALUES(:attempt,:question,:option,:client,:timestamp,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE option_snapshot_id=VALUES(option_snapshot_id),client_answer_id=VALUES(client_answer_id),client_timestamp=VALUES(client_timestamp),answered_at=UTC_TIMESTAMP()');$save->execute(['attempt'=>$attempt,'question'=>$row['question_id'],'option'=>$row['option_id'],'client'=>$client,'timestamp'=>$timestamp]);return'saved';}
    public function flag(int$attempt,string$question,bool$set): void {$s=$this->pdo->prepare('SELECT id FROM attempt_question_snapshots WHERE attempt_id=:attempt AND public_id=:question');$s->execute(['attempt'=>$attempt,'question'=>$question]);$qid=$s->fetchColumn();if(!$qid)throw new \DomainException('Soal tidak termasuk snapshot attempt.');$sql=$set?'INSERT IGNORE INTO attempt_flags(attempt_id,attempt_question_snapshot_id,created_at) VALUES(:attempt,:question,UTC_TIMESTAMP())':'DELETE FROM attempt_flags WHERE attempt_id=:attempt AND attempt_question_snapshot_id=:question';$this->pdo->prepare($sql)->execute(['attempt'=>$attempt,'question'=>$qid]);}
    public function scoreRows(int$attempt): array {$s=$this->pdo->prepare('SELECT qs.question_id,qs.topic_name topic,qs.category_name category,qs.difficulty,qs.correct_option_public_id correct_option_id,selected.source_option_public_id selected_option_id FROM attempt_question_snapshots qs LEFT JOIN attempt_answers a ON a.attempt_question_snapshot_id=qs.id LEFT JOIN attempt_option_snapshots selected ON selected.id=a.option_snapshot_id WHERE qs.attempt_id=:id ORDER BY qs.question_order');$s->execute(['id'=>$attempt]);return$s->fetchAll();}
    public function persistResult(array$a,array$result,string$status): void {$this->pdo->prepare('UPDATE attempts SET status=:status,submitted_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=:id')->execute(['status'=>$status,'id'=>$a['id']]);$json=json_encode($result,JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE);$this->pdo->prepare('INSERT INTO attempt_results(attempt_id,total_questions,answered,unanswered,correct,incorrect,raw_score,percentage_score,duration_seconds,average_time_seconds,result_json,calculated_at) VALUES(:attempt,:total,:answered,:unanswered,:correct,:incorrect,:raw,:percentage,:duration,:average,:json,UTC_TIMESTAMP())')->execute(['attempt'=>$a['id'],'total'=>$result['total_questions'],'answered'=>$result['answered'],'unanswered'=>$result['unanswered'],'correct'=>$result['correct'],'incorrect'=>$result['incorrect'],'raw'=>$result['raw_score'],'percentage'=>$result['percentage_score'],'duration'=>$result['duration_seconds'],'average'=>$result['average_time_seconds'],'json'=>$json]);$analytics=$this->pdo->prepare('INSERT INTO attempt_analytics(attempt_id,dimension_type,dimension_key,total,correct,incorrect,unanswered,percentage) VALUES(:attempt,:dimension_type,:dimension_key,:total,:correct,:incorrect,:unanswered,:percentage)');foreach($result['analytics']as$row)$analytics->execute(['attempt'=>$a['id'],...$row]);$history=$this->pdo->prepare('INSERT INTO user_question_histories(user_id,question_id,attempts_count,correct_count,incorrect_count,last_answered_at) VALUES(:user,:question,1,:correct,:incorrect,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE attempts_count=attempts_count+1,correct_count=correct_count+VALUES(correct_count),incorrect_count=incorrect_count+VALUES(incorrect_count),last_answered_at=UTC_TIMESTAMP()');foreach($this->scoreRows((int)$a['id'])as$row)if($row['selected_option_id']!==null)$history->execute(['user'=>$a['user_id'],'question'=>$row['question_id'],'correct'=>(int)($row['selected_option_id']===$row['correct_option_id']),'incorrect'=>(int)($row['selected_option_id']!==$row['correct_option_id'])]);}
    public function event(int$attempt,?int$user,string$type,array$payload=[]):void{$this->pdo->prepare('INSERT INTO attempt_events(public_id,attempt_id,user_id,event_type,payload_json,occurred_at) VALUES(:id,:attempt,:user,:type,:payload,UTC_TIMESTAMP())')->execute(['id'=>QuestionRepository::uuid(),'attempt'=>$attempt,'user'=>$user,'type'=>$type,'payload'=>json_encode($payload,JSON_THROW_ON_ERROR)]);}
    public function result(int$attempt):?array{$s=$this->pdo->prepare('SELECT result_json FROM attempt_results WHERE attempt_id=:id');$s->execute(['id'=>$attempt]);$v=$s->fetchColumn();return is_string($v)?json_decode($v,true):null;}
    public function review(int$attempt,bool$answeredOnly=false):array{$sql='SELECT qs.public_id id,qs.question_order,qs.stem,qs.explanation,qs.correct_option_public_id correct_option_id,selected.source_option_public_id selected_option_id,o.public_id option_id,o.option_order,o.content,o.explanation option_explanation FROM attempt_question_snapshots qs JOIN attempt_option_snapshots o ON o.attempt_question_snapshot_id=qs.id LEFT JOIN attempt_answers a ON a.attempt_question_snapshot_id=qs.id LEFT JOIN attempt_option_snapshots selected ON selected.id=a.option_snapshot_id WHERE qs.attempt_id=:id'.($answeredOnly?' AND a.id IS NOT NULL':'').' ORDER BY qs.question_order,o.option_order';$s=$this->pdo->prepare($sql);$s->execute(['id'=>$attempt]);$out=[];foreach($s->fetchAll()as$r){$key=$r['id'];$out[$key]??=['id'=>$key,'order'=>(int)$r['question_order'],'stem'=>$r['stem'],'explanation'=>$r['explanation'],'correct_option_id'=>$r['correct_option_id'],'selected_option_id'=>$r['selected_option_id'],'is_correct'=>$r['selected_option_id']!==null&&$r['selected_option_id']===$r['correct_option_id'],'options'=>[]];$out[$key]['options'][]=['id'=>$r['option_id'],'order'=>(int)$r['option_order'],'content'=>$r['content'],'explanation'=>$r['option_explanation']];}return array_values($out);}
    public function myAttempts(int$user):array{$s=$this->pdo->prepare('SELECT a.public_id id,a.status,q.name,q.mode,a.started_at,a.expires_at,a.submitted_at,r.percentage_score FROM attempts a JOIN quiz_templates q ON q.id=a.template_id LEFT JOIN attempt_results r ON r.attempt_id=a.id WHERE a.user_id=:user ORDER BY a.created_at DESC');$s->execute(['user'=>$user]);return$s->fetchAll();}
    public function aggregate(int$user):array{$s=$this->pdo->prepare('SELECT COUNT(r.id) attempts,COALESCE(AVG(r.percentage_score),0) average_score,COALESCE(SUM(r.correct),0) correct,COALESCE(SUM(r.incorrect),0) incorrect FROM attempts a JOIN attempt_results r ON r.attempt_id=a.id WHERE a.user_id=:user');$s->execute(['user'=>$user]);return$s->fetch();}
    public function questionList(int$user,string$type):array{$join=$type==='bookmark'?'user_bookmarks x':'user_question_histories x';$condition=$type==='bookmark'?'':' AND x.incorrect_count>x.correct_count';$s=$this->pdo->prepare("SELECT q.public_id id,q.stem,q.difficulty,c.name category,t.name topic FROM {$join} JOIN questions q ON q.id=x.question_id JOIN question_categories c ON c.id=q.category_id JOIN question_topics t ON t.id=q.topic_id WHERE x.user_id=:user{$condition} ORDER BY q.updated_at DESC");$s->execute(['user'=>$user]);return$s->fetchAll();}
    public function expired():array{return$this->pdo->query("SELECT public_id,user_id FROM attempts WHERE status='active' AND expires_at<=UTC_TIMESTAMP() ORDER BY expires_at LIMIT 100")->fetchAll();}
}
