<?php

declare(strict_types=1);

namespace Sinaesta\Billing\Application;

use PDO;
use Sinaesta\Billing\Infrastructure\BillingRepository;
use Sinaesta\Billing\Infrastructure\PaymentGatewayRegistry;
use Sinaesta\Shared\Http\HttpException;

final readonly class BillingService
{
    public function __construct(private BillingRepository $repository, private PaymentGatewayRegistry $gateways) {}
    public function packages(?string $id=null): array { $rows=$this->repository->plans($id);if($id!==null&&$rows===[])throw new HttpException(404,'Paket tidak ditemukan.');return $id===null?$rows:$rows[0]; }

    public function checkout(int $userId,array $input): array
    {
        $planId=is_string($input['package_id']??null)?$input['package_id']:'';$priceId=is_string($input['price_id']??null)?$input['price_id']:null;$gateway=is_string($input['gateway']??null)?$input['gateway']:'local';
        if($planId===''||isset($input['total']))throw new HttpException(422,'Input checkout tidak valid.',['package_id'=>['Paket wajib diisi dan total tidak boleh ditentukan klien.']]);
        $price=$this->repository->priceForCheckout($planId,$priceId);if(!$price)throw new HttpException(422,'Harga paket tidak tersedia.');
        $subtotal=(int)$price['amount'];$voucher=null;$discount=0;
        if(is_string($input['voucher_code']??null)&&trim($input['voucher_code'])!==''){$voucher=$this->repository->validVoucher($input['voucher_code'],(int)$price['plan_id'],$userId,$subtotal);if(!$voucher)throw new HttpException(422,'Voucher tidak valid atau sudah kedaluwarsa.');$discount=$voucher['discount_type']==='percentage'?(int)floor($subtotal*(int)$voucher['discount_value']/100):(int)$voucher['discount_value'];if($voucher['max_discount_amount']!==null)$discount=min($discount,(int)$voucher['max_discount_amount']);$discount=min($subtotal,$discount);}
        $total=$subtotal-$discount;$transactionId=bin2hex(random_bytes(16));$invoiceId=bin2hex(random_bytes(16));$expires=(new \DateTimeImmutable('+24 hours'))->format('Y-m-d H:i:s');$pdo=$this->repository->pdo();
        $pdo->beginTransaction();try{$s=$pdo->prepare("INSERT INTO transactions(public_id,user_id,status,subtotal,discount_amount,total,currency,gateway,expires_at,created_at,updated_at) VALUES(:id,:user,'pending',:subtotal,:discount,:total,:currency,:gateway,:expires,UTC_TIMESTAMP(),UTC_TIMESTAMP())");$s->execute(['id'=>$transactionId,'user'=>$userId,'subtotal'=>$subtotal,'discount'=>$discount,'total'=>$total,'currency'=>$price['currency'],'gateway'=>$gateway,'expires'=>$expires]);$internal=(int)$pdo->lastInsertId();$item=$pdo->prepare('INSERT INTO transaction_items(public_id,transaction_id,plan_id,price_id,description,quantity,unit_amount,total_amount,created_at) VALUES(:id,:transaction,:plan,:price,:description,1,:amount,:amount,UTC_TIMESTAMP())');$item->execute(['id'=>bin2hex(random_bytes(16)),'transaction'=>$internal,'plan'=>$price['plan_id'],'price'=>$price['price_id'],'description'=>$price['name'],'amount'=>$subtotal]);$invoice=$this->gateways->get($gateway)->createInvoice(['external_id'=>$transactionId,'amount'=>$total,'currency'=>$price['currency'],'expires_at'=>$expires]);$u=$pdo->prepare('UPDATE transactions SET gateway_reference=:reference WHERE id=:id');$u->execute(['reference'=>$invoice['external_id'],'id'=>$internal]);$i=$pdo->prepare("INSERT INTO invoices(public_id,transaction_id,gateway_invoice_id,status,payment_url,amount,currency,expires_at,created_at,updated_at) VALUES(:public,:transaction,:gateway,'pending',:url,:amount,:currency,:expires,UTC_TIMESTAMP(),UTC_TIMESTAMP())");$i->execute(['public'=>$invoiceId,'transaction'=>$internal,'gateway'=>$invoice['external_id'],'url'=>$invoice['payment_url'],'amount'=>$total,'currency'=>$price['currency'],'expires'=>$expires]);if($voucher){$vu=$pdo->prepare('INSERT INTO voucher_usages(public_id,voucher_id,user_id,transaction_id,discount_amount,created_at) VALUES(:id,:voucher,:user,:transaction,:discount,UTC_TIMESTAMP())');$vu->execute(['id'=>bin2hex(random_bytes(16)),'voucher'=>$voucher['id'],'user'=>$userId,'transaction'=>$internal,'discount'=>$discount]);}$pdo->commit();return ['transaction_id'=>$transactionId,'invoice_id'=>$invoiceId,'subtotal'=>$subtotal,'discount'=>$discount,'total'=>$total,'currency'=>$price['currency'],'payment_url'=>$invoice['payment_url'],'expires_at'=>$expires];}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }

    public function webhook(string $gateway,array $headers,string $rawBody): void
    {
        $adapter=$this->gateways->get($gateway);if(!$adapter->verifyWebhook($headers,$rawBody))throw new HttpException(401,'Signature webhook tidak valid.');$event=json_decode($rawBody,true,16,JSON_THROW_ON_ERROR);foreach(['event_id','external_id','status','amount','currency'] as $key){if(!isset($event[$key]))throw new HttpException(422,'Payload webhook tidak lengkap.');}
        $pdo=$this->repository->pdo();$pdo->beginTransaction();try{$seen=$pdo->prepare('SELECT id FROM payment_webhooks WHERE gateway=:gateway AND event_id=:event LIMIT 1');$seen->execute(['gateway'=>$gateway,'event'=>$event['event_id']]);if($seen->fetch()){$pdo->commit();return;}$find=$pdo->prepare('SELECT id,user_id,status,total,currency FROM transactions WHERE gateway=:gateway AND gateway_reference=:external FOR UPDATE');$find->execute(['gateway'=>$gateway,'external'=>$event['external_id']]);$transaction=$find->fetch();if(!$transaction||(int)$transaction['total']!==(int)$event['amount']||$transaction['currency']!==$event['currency'])throw new HttpException(422,'Referensi atau nominal pembayaran tidak cocok.');$store=$pdo->prepare("INSERT INTO payment_webhooks(public_id,gateway,event_id,payload_hash,processing_status,received_at,processed_at) VALUES(:id,:gateway,:event,:hash,'processed',UTC_TIMESTAMP(),UTC_TIMESTAMP())");$store->execute(['id'=>bin2hex(random_bytes(16)),'gateway'=>$gateway,'event'=>$event['event_id'],'hash'=>hash('sha256',$rawBody)]);if($event['status']==='paid'&&$transaction['status']!=='paid'){$update=$pdo->prepare("UPDATE transactions SET status='paid',paid_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE id=:id");$update->execute(['id'=>$transaction['id']]);$pdo->prepare("UPDATE invoices SET status='paid',paid_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE transaction_id=:id")->execute(['id'=>$transaction['id']]);$this->activate((int)$transaction['id'],(int)$transaction['user_id']);}$history=$pdo->prepare('INSERT INTO payment_status_histories(public_id,transaction_id,from_status,to_status,source,created_at) VALUES(:public,:transaction,:from_status,:to_status,\'webhook\',UTC_TIMESTAMP())');$history->execute(['public'=>bin2hex(random_bytes(16)),'transaction'=>$transaction['id'],'from_status'=>$transaction['status'],'to_status'=>$event['status']]);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }

    private function activate(int $transactionId,int $userId): void
    {
        $pdo=$this->repository->pdo();$s=$pdo->prepare('SELECT ti.plan_id,p.plan_type,p.duration_days FROM transaction_items ti JOIN subscription_plans p ON p.id=ti.plan_id WHERE ti.transaction_id=:id LIMIT 1');$s->execute(['id'=>$transactionId]);$plan=$s->fetch();if(!$plan)return;$expires=$plan['duration_days']===null?null:(new \DateTimeImmutable('+'.(int)$plan['duration_days'].' days'))->format('Y-m-d H:i:s');
        if($plan['plan_type']==='token'){$wallet=$pdo->prepare('INSERT INTO tryout_token_wallets(public_id,user_id,balance,expires_at,created_at,updated_at) VALUES(:id,:user,0,:expires,UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE expires_at=GREATEST(expires_at,VALUES(expires_at)),updated_at=UTC_TIMESTAMP()');$wallet->execute(['id'=>bin2hex(random_bytes(16)),'user'=>$userId,'expires'=>$expires]);$token=$pdo->prepare("SELECT integer_value FROM plan_feature_values v JOIN plan_features f ON f.id=v.feature_id WHERE v.plan_id=:plan AND f.entitlement_key='tryout_token_balance'");$token->execute(['plan'=>$plan['plan_id']]);$amount=(int)$token->fetchColumn();$pdo->prepare('UPDATE tryout_token_wallets SET balance=balance+:amount WHERE user_id=:user')->execute(['amount'=>$amount,'user'=>$userId]);$pdo->prepare("INSERT INTO tryout_token_transactions(public_id,wallet_id,transaction_id,type,amount,description,created_at) SELECT :id,id,:transaction,'credit',:amount,'Pembelian token',UTC_TIMESTAMP() FROM tryout_token_wallets WHERE user_id=:user")->execute(['id'=>bin2hex(random_bytes(16)),'transaction'=>$transactionId,'amount'=>$amount,'user'=>$userId]);return;}
        $subscription=bin2hex(random_bytes(16));$pdo->prepare("INSERT INTO subscriptions(public_id,user_id,plan_id,source_transaction_id,status,starts_at,expires_at,auto_renew,created_at,updated_at) VALUES(:id,:user,:plan,:transaction,'active',UTC_TIMESTAMP(),:expires,0,UTC_TIMESTAMP(),UTC_TIMESTAMP())")->execute(['id'=>$subscription,'user'=>$userId,'plan'=>$plan['plan_id'],'transaction'=>$transactionId,'expires'=>$expires]);$subscriptionId=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO subscription_histories(public_id,subscription_id,event_type,to_status,created_at) VALUES(:id,:subscription,'activated','active',UTC_TIMESTAMP())")->execute(['id'=>bin2hex(random_bytes(16)),'subscription'=>$subscriptionId]);$pdo->prepare('INSERT INTO user_entitlements(public_id,user_id,subscription_id,entitlement_key,value_type,integer_value,boolean_value,string_value,starts_at,expires_at,created_at) SELECT LOWER(HEX(RANDOM_BYTES(16))),:user,:subscription,f.entitlement_key,v.value_type,v.integer_value,v.boolean_value,v.string_value,UTC_TIMESTAMP(),:expires,UTC_TIMESTAMP() FROM plan_feature_values v JOIN plan_features f ON f.id=v.feature_id WHERE v.plan_id=:plan')->execute(['user'=>$userId,'subscription'=>$subscriptionId,'expires'=>$expires,'plan'=>$plan['plan_id']]);
    }
}
